"""
email_report.py — Send the morning briefing email.

Loads reports/morning_briefing_YYYY-MM-DD.txt and sends it via SMTP/TLS.

Exit codes:
    0  — email sent successfully
    1  — SMTP or configuration failure
"""

from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

from src.config import get_config
from src.email_render import to_html
from src.helpers import data_path, log, report_path, today_str
from src.mailer import send_email
from src.ops import degraded_banner, degraded_subject_tag


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_briefing(path: str) -> tuple[str, bool]:
    """Load the morning briefing text.

    Returns (body_text, is_fallback).
    """
    p = Path(path)
    if p.exists():
        try:
            content = p.read_text(encoding="utf-8")
            if content.strip():
                return content, False
            log("email_report: briefing file exists but is empty — using fallback", "WARNING")
        except OSError as exc:
            log(f"email_report: could not read briefing file — {exc}", "WARNING")

    fallback = (
        "MORNING BRIEFING NOT GENERATED\n\n"
        "The pipeline ran but the morning briefing was not produced.\n\n"
        "Likely causes:\n"
        "  1. No racecard data fetched (run_daily.py failed or no racing today)\n"
        "  2. nap_selector_v3.py returned BLOCKED\n"
        "  3. morning_briefing_report.py crashed (check PythonAnywhere logs)\n\n"
        "Check: reports/ and data/ directories for today's date."
    )
    log("email_report: using fallback body — briefing file missing or empty", "WARNING")
    return fallback, True


def _load_ai_briefing(date_str: str) -> str:
    """Return the AI natural-language briefing if present and non-empty, else ''.

    A no-op when briefing_writer_ai degraded (no key / stub) — the templated
    briefing remains the source of truth and is unaffected.
    """
    p = Path(report_path(f"ai_briefing_{date_str}.txt"))
    if not p.exists():
        return ""
    try:
        content = p.read_text(encoding="utf-8").strip()
    except OSError as exc:
        log(f"email_report: could not read AI briefing — {exc}", "WARNING")
        return ""
    # Skip degraded stubs so we never prepend a placeholder above the real brief.
    if not content or "STUB" in content[:200].upper() or "unavailable" in content[:200].lower():
        return ""
    return content


def _build_subject(date_str: str, is_fallback: bool) -> str:
    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        day_name = dt.strftime("%A")
    except ValueError:
        day_name = "Unknown"

    if is_fallback:
        return f"Racing Intelligence | Morning Briefing | {day_name} {date_str} (MISSING)"
    return f"Racing Intelligence | Morning Briefing | {day_name} {date_str}"


def _build_body(body_text: str) -> str:
    footer = (
        f"\n\n---\n"
        f"Generated by Racing Intelligence System v3 | "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )
    return body_text + footer


def _write_flag(flag_path: str) -> None:
    try:
        Path(flag_path).write_text(
            datetime.now().isoformat(), encoding="utf-8"
        )
    except OSError as exc:
        log(f"email_report: could not write flag file {flag_path} — {exc}", "WARNING")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    """Load briefing, send email. Returns exit code."""
    log("email_report.py started")

    date_str = today_str()

    # --- Config -----------------------------------------------------------------
    try:
        cfg = get_config()
    except KeyError as exc:
        log(f"email_report: missing configuration key — {exc}", "ERROR")
        return 1

    # --- Load briefing ----------------------------------------------------------
    briefing_path = report_path(f"morning_briefing_{date_str}.txt")
    body_text, is_fallback = _load_briefing(briefing_path)

    # Prepend the AI natural-language briefing when available (no-op if absent).
    ai_brief = _load_ai_briefing(date_str)
    if ai_brief:
        sep = "─" * 60
        body_text = f"{ai_brief}\n\n{sep}\n\n{body_text}"
        log("email_report: prepended AI natural-language briefing")

    subject = _build_subject(date_str, is_fallback) + degraded_subject_tag("morning", date_str)
    # A loud banner if any pipeline step failed, so a degraded run is never
    # mistaken for a clean one. It headlines the plain-text fallback and becomes
    # the red callout in the HTML version.
    banner = degraded_banner("morning", date_str)
    plain_body = _build_body(banner + body_text)

    # HTML version (multipart/alternative — plain text above is the fallback).
    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        subtitle = f"Morning Briefing — {dt.strftime('%a')} {date_str}"
    except ValueError:
        subtitle = f"Morning Briefing — {date_str}"
    if is_fallback:
        subtitle += " (MISSING)"
    html_body = to_html("Racing Intelligence", subtitle, body_text, degraded_note=banner)

    log(f"email_report: subject='{subject}'")
    log(f"email_report: sending to {cfg.email_recipient} via {cfg.smtp_host}:{cfg.smtp_port}")

    # --- Send (single shared SMTP path; HTML + plain-text fallback) --------------
    failed_flag = data_path(f"email_morning_failed_{date_str}.flag")
    sent_flag = data_path(f"email_morning_sent_{date_str}.flag")

    if not send_email(subject, plain_body, html_body=html_body):
        log("email_report: send failed — see mailer log above", "ERROR")
        _write_flag(failed_flag)
        return 1

    _write_flag(sent_flag)
    log("email_report: morning briefing email sent successfully")
    print(f"email_report: SUCCESS — sent to {cfg.email_recipient}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
