"""
email_market_update.py — Send the market update email (early afternoon).

Loads:
    reports/final_nap_decision_YYYY-MM-DD.txt  (primary — MUST exist for full email)
    reports/market_movers_YYYY-MM-DD.txt        (appended if available)
    reports/non_runners_YYYY-MM-DD.txt          (appended if available)

This email is ALWAYS sent, even when upstream reports are missing.
A missing final_nap_decision triggers a BLOCKED subject/body but still sends.

Exit codes:
    0  — email sent successfully
    1  — SMTP or configuration failure
"""

from __future__ import annotations

import smtplib
import sys
from datetime import datetime
from email.mime.text import MIMEText
from pathlib import Path
from typing import Optional

from src.config import get_config
from src.helpers import data_path, log, report_path, today_str


# ---------------------------------------------------------------------------
# File loading helpers
# ---------------------------------------------------------------------------

def _try_read(path: str) -> Optional[str]:
    """Read a text file. Returns None (with a WARNING log) if missing/unreadable."""
    p = Path(path)
    if not p.exists():
        log(f"email_market_update: file not found — {path}", "WARNING")
        return None
    try:
        return p.read_text(encoding="utf-8")
    except OSError as exc:
        log(f"email_market_update: could not read {path} — {exc}", "WARNING")
        return None


def _section_header(title: str) -> str:
    bar = "=" * 60
    return f"\n{bar}\n{title}\n{bar}\n"


# ---------------------------------------------------------------------------
# Email composition
# ---------------------------------------------------------------------------

def _compose_email(
    date_str: str,
    nap_text: Optional[str],
    movers_text: Optional[str],
    nr_text: Optional[str],
) -> tuple[str, str]:
    """Build (subject, body) for the market update email.

    If nap_text is None the email is flagged as BLOCKED.
    The other two sections are appended when available, with a clear note
    when they are missing so the recipient always knows what's included.
    """
    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        day_name = dt.strftime("%A")
    except ValueError:
        day_name = "Unknown"

    blocked = nap_text is None

    if blocked:
        subject = f"Racing Intelligence | BLOCKED | {date_str}"
        nap_section = (
            "FINAL NAP DECISION — NOT AVAILABLE\n\n"
            "The final NAP decision report could not be found.\n"
            "This may indicate a pipeline failure upstream.\n"
            "Please check the pipeline logs.\n"
        )
    else:
        subject = f"Racing Intelligence | Market Update | {day_name} {date_str}"
        nap_section = nap_text

    parts: list[str] = [
        _section_header("FINAL NAP DECISION"),
        nap_section,
    ]

    parts.append(_section_header("MARKET MOVERS"))
    if movers_text:
        parts.append(movers_text)
    else:
        parts.append(
            "[Market movers report not available — "
            "market_movers.py may not have run yet]\n"
        )

    parts.append(_section_header("NON-RUNNER SCAN"))
    if nr_text:
        parts.append(nr_text)
    else:
        parts.append(
            "[Non-runner scan report not available — "
            "non_runner_scan.py may not have run yet]\n"
        )

    footer = (
        f"\n---\n"
        f"Generated by Racing Intelligence System v3 | "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )
    parts.append(footer)

    body = "\n".join(parts)
    return subject, body


# ---------------------------------------------------------------------------
# Flag file helper
# ---------------------------------------------------------------------------

def _write_flag(flag_path: str) -> None:
    try:
        Path(flag_path).write_text(datetime.now().isoformat(), encoding="utf-8")
    except OSError as exc:
        log(f"email_market_update: could not write flag {flag_path} — {exc}", "WARNING")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    """Load reports, compose, send email. Returns exit code."""
    log("email_market_update.py started")

    date_str = today_str()

    # --- Config -----------------------------------------------------------------
    try:
        cfg = get_config()
    except KeyError as exc:
        log(f"email_market_update: missing configuration key — {exc}", "ERROR")
        return 1

    # --- Load reports (CRITICAL: never crash on missing files) ------------------
    nap_path    = report_path(f"final_nap_decision_{date_str}.txt")
    movers_path = report_path(f"market_movers_{date_str}.txt")
    nr_path     = report_path(f"non_runners_{date_str}.txt")

    nap_text    = _try_read(nap_path)
    movers_text = _try_read(movers_path)
    nr_text     = _try_read(nr_path)

    missing_files: list[str] = []
    if nap_text is None:
        missing_files.append(f"final_nap_decision_{date_str}.txt")
    if movers_text is None:
        missing_files.append(f"market_movers_{date_str}.txt")
    if nr_text is None:
        missing_files.append(f"non_runners_{date_str}.txt")

    if missing_files:
        log(
            f"email_market_update: missing reports — {', '.join(missing_files)}",
            "WARNING" if nap_text else "ERROR",
        )

    # If ALL reports are missing there is nothing useful to send — send a clear
    # PIPELINE FAILURE alert rather than an email full of placeholder text.
    if nap_text is None and movers_text is None and nr_text is None:
        log("email_market_update: ALL reports missing — sending PIPELINE FAILURE alert", "ERROR")
        nap_text = (
            "PIPELINE FAILURE — NO REPORTS GENERATED\n\n"
            "None of the expected market update reports were found.\n\n"
            f"Expected files:\n"
            f"  • final_nap_decision_{date_str}.txt\n"
            f"  • market_movers_{date_str}.txt\n"
            f"  • non_runners_{date_str}.txt\n\n"
            "The market update pipeline ran but upstream steps all failed.\n"
            "Check PythonAnywhere task logs for errors.\n"
        )

    # --- Compose email ----------------------------------------------------------
    subject, body = _compose_email(date_str, nap_text, movers_text, nr_text)

    log(f"email_market_update: subject='{subject}'")
    log(
        f"email_market_update: sending to {cfg.email_recipient} "
        f"via {cfg.smtp_host}:{cfg.smtp_port}"
    )

    # --- Build MIME message -----------------------------------------------------
    msg = MIMEText(body, "plain", "utf-8")
    msg["Subject"] = subject
    msg["From"] = cfg.email_sender
    msg["To"] = cfg.email_recipient

    # --- Send (CRITICAL: always attempt SMTP — never let missing files stop send) -
    sent_flag = data_path(f"email_market_sent_{date_str}.flag")

    try:
        with smtplib.SMTP(cfg.smtp_host, cfg.smtp_port, timeout=30) as smtp:
            smtp.ehlo()
            smtp.starttls()
            smtp.ehlo()
            smtp.login(cfg.email_sender, cfg.email_password)
            smtp.sendmail(cfg.email_sender, cfg.email_recipient, msg.as_string())
    except smtplib.SMTPException as exc:
        log(f"email_market_update: SMTP error — {exc}", "ERROR")
        return 1
    except OSError as exc:
        log(f"email_market_update: network/OS error — {exc}", "ERROR")
        return 1

    _write_flag(sent_flag)
    log("email_market_update: market update email sent successfully")
    print(f"email_market_update: SUCCESS — sent to {cfg.email_recipient}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
