"""
email_report.py — Send the morning briefing email.

Loads reports/morning_briefing_YYYY-MM-DD.txt and sends it via SMTP/TLS.

Exit codes:
    0  — email sent successfully
    1  — SMTP or configuration failure
"""

from __future__ import annotations

import smtplib
import sys
from datetime import datetime
from email.mime.text import MIMEText
from pathlib import Path

from src.config import get_config
from src.helpers import data_path, log, report_path, today_str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_briefing(path: str) -> tuple[str, bool]:
    """Load the morning briefing text.

    Returns (body_text, is_fallback).
    """
    p = Path(path)
    if p.exists():
        try:
            content = p.read_text(encoding="utf-8")
            if content.strip():
                return content, False
            log("email_report: briefing file exists but is empty — using fallback", "WARNING")
        except OSError as exc:
            log(f"email_report: could not read briefing file — {exc}", "WARNING")

    fallback = (
        "MORNING BRIEFING NOT GENERATED\n\n"
        "The pipeline ran but the morning briefing was not produced.\n\n"
        "Likely causes:\n"
        "  1. No racecard data fetched (run_daily.py failed or no racing today)\n"
        "  2. nap_selector_v3.py returned BLOCKED\n"
        "  3. morning_briefing_report.py crashed (check PythonAnywhere logs)\n\n"
        "Check: reports/ and data/ directories for today's date."
    )
    log("email_report: using fallback body — briefing file missing or empty", "WARNING")
    return fallback, True


def _build_subject(date_str: str, is_fallback: bool) -> str:
    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        day_name = dt.strftime("%A")
    except ValueError:
        day_name = "Unknown"

    if is_fallback:
        return f"Racing Intelligence | Morning Briefing | {day_name} {date_str} (MISSING)"
    return f"Racing Intelligence | Morning Briefing | {day_name} {date_str}"


def _build_body(body_text: str) -> str:
    footer = (
        f"\n\n---\n"
        f"Generated by Racing Intelligence System v3 | "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )
    return body_text + footer


def _write_flag(flag_path: str) -> None:
    try:
        Path(flag_path).write_text(
            datetime.now().isoformat(), encoding="utf-8"
        )
    except OSError as exc:
        log(f"email_report: could not write flag file {flag_path} — {exc}", "WARNING")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    """Load briefing, send email. Returns exit code."""
    log("email_report.py started")

    date_str = today_str()

    # --- Config -----------------------------------------------------------------
    try:
        cfg = get_config()
    except KeyError as exc:
        log(f"email_report: missing configuration key — {exc}", "ERROR")
        return 1

    # --- Load briefing ----------------------------------------------------------
    briefing_path = report_path(f"morning_briefing_{date_str}.txt")
    body_text, is_fallback = _load_briefing(briefing_path)

    subject = _build_subject(date_str, is_fallback)
    body = _build_body(body_text)

    log(f"email_report: subject='{subject}'")
    log(f"email_report: sending to {cfg.email_recipient} via {cfg.smtp_host}:{cfg.smtp_port}")

    # --- Build MIME message -----------------------------------------------------
    msg = MIMEText(body, "plain", "utf-8")
    msg["Subject"] = subject
    msg["From"] = cfg.email_sender
    msg["To"] = cfg.email_recipient

    # --- Send via SMTP/TLS -------------------------------------------------------
    failed_flag = data_path(f"email_morning_failed_{date_str}.flag")
    sent_flag = data_path(f"email_morning_sent_{date_str}.flag")

    try:
        with smtplib.SMTP(cfg.smtp_host, cfg.smtp_port, timeout=30) as smtp:
            smtp.ehlo()
            smtp.starttls()
            smtp.ehlo()
            smtp.login(cfg.email_sender, cfg.email_password)
            smtp.sendmail(cfg.email_sender, cfg.email_recipient, msg.as_string())
    except smtplib.SMTPException as exc:
        log(f"email_report: SMTP error — {exc}", "ERROR")
        _write_flag(failed_flag)
        return 1
    except OSError as exc:
        log(f"email_report: network/OS error — {exc}", "ERROR")
        _write_flag(failed_flag)
        return 1

    _write_flag(sent_flag)
    log("email_report: morning briefing email sent successfully")
    print(f"email_report: SUCCESS — sent to {cfg.email_recipient}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
