"""
email_audit.py — Send the evening audit email.

Loads:
    reports/results_audit_YYYY-MM-DD.txt          (primary)
    reports/profit_report_YYYY-MM-DD.txt           (primary)
    reports/performance_log_summary_YYYY-MM-DD.txt (optional)

If none are available, sends a "not yet available" notice email.

Exit codes:
    0  — email sent successfully
    1  — SMTP or configuration failure
"""

from __future__ import annotations

import smtplib
import sys
from datetime import datetime
from email.mime.text import MIMEText
from pathlib import Path
from typing import Optional

from src.config import get_config
from src.helpers import data_path, log, report_path, today_str


# ---------------------------------------------------------------------------
# File loading helpers
# ---------------------------------------------------------------------------

def _try_read(path: str) -> Optional[str]:
    """Read a text file. Returns None (with WARNING log) if missing/unreadable."""
    p = Path(path)
    if not p.exists():
        log(f"email_audit: file not found — {path}", "WARNING")
        return None
    try:
        return p.read_text(encoding="utf-8")
    except OSError as exc:
        log(f"email_audit: could not read {path} — {exc}", "WARNING")
        return None


def _section_header(title: str) -> str:
    bar = "=" * 60
    return f"\n{bar}\n{title}\n{bar}\n"


# ---------------------------------------------------------------------------
# Email composition
# ---------------------------------------------------------------------------

def _compose_email(
    date_str: str,
    results_text: Optional[str],
    profit_text: Optional[str],
    perf_text: Optional[str],
) -> tuple[str, str]:
    """Build (subject, body) for the evening audit email."""
    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        day_name = dt.strftime("%A")
    except ValueError:
        day_name = "Unknown"

    subject = f"Racing Intelligence | Evening Audit | {day_name} {date_str}"

    any_available = results_text or profit_text or perf_text

    if not any_available:
        body = (
            f"RACING INTELLIGENCE SYSTEM — EVENING AUDIT\n"
            f"Date: {date_str}\n\n"
            "Evening audit reports are not yet available.\n"
            "Results, profit analysis, and performance logs will be included\n"
            "once the auditor pipeline has completed.\n\n"
            "Please check the evening_audit_pipeline logs for details.\n"
            f"\n---\n"
            f"Generated by Racing Intelligence System v3 | "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        )
        return subject, body

    parts: list[str] = [
        f"RACING INTELLIGENCE SYSTEM — EVENING AUDIT",
        f"Date: {date_str}",
        "",
    ]

    # Results audit
    parts.append(_section_header("RESULTS AUDIT"))
    if results_text:
        parts.append(results_text)
    else:
        parts.append("[Results audit not available — results_auditor.py may not have run]\n")

    # Profit report
    parts.append(_section_header("PROFIT REPORT"))
    if profit_text:
        parts.append(profit_text)
    else:
        parts.append("[Profit report not available — profit_report.py may not have run]\n")

    # Performance log summary (optional — only include section if present)
    if perf_text:
        parts.append(_section_header("PERFORMANCE LOG SUMMARY"))
        parts.append(perf_text)

    footer = (
        f"\n---\n"
        f"Generated by Racing Intelligence System v3 | "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )
    parts.append(footer)

    body = "\n".join(parts)
    return subject, body


# ---------------------------------------------------------------------------
# Flag file helper
# ---------------------------------------------------------------------------

def _write_flag(flag_path: str) -> None:
    try:
        Path(flag_path).write_text(datetime.now().isoformat(), encoding="utf-8")
    except OSError as exc:
        log(f"email_audit: could not write flag {flag_path} — {exc}", "WARNING")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    """Load audit reports, compose, send email. Returns exit code."""
    log("email_audit.py started")

    date_str = today_str()

    # --- Config -----------------------------------------------------------------
    try:
        cfg = get_config()
    except KeyError as exc:
        log(f"email_audit: missing configuration key — {exc}", "ERROR")
        return 1

    # --- Load reports -----------------------------------------------------------
    results_path = report_path(f"results_audit_{date_str}.txt")
    profit_path  = report_path(f"profit_report_{date_str}.txt")
    perf_path    = report_path(f"performance_log_summary_{date_str}.txt")

    results_text = _try_read(results_path)
    profit_text  = _try_read(profit_path)
    perf_text    = _try_read(perf_path)  # optional — no warning needed if absent

    available: list[str] = []
    unavailable: list[str] = []

    for label, text, fname in [
        ("results_audit",          results_text, f"results_audit_{date_str}.txt"),
        ("profit_report",          profit_text,  f"profit_report_{date_str}.txt"),
        ("performance_log_summary", perf_text,   f"performance_log_summary_{date_str}.txt"),
    ]:
        if text is not None:
            available.append(label)
        else:
            unavailable.append(fname)

    log(f"email_audit: available reports — {available or ['none']}")
    if unavailable:
        log(f"email_audit: unavailable reports — {unavailable}", "WARNING")

    # --- Compose email ----------------------------------------------------------
    subject, body = _compose_email(date_str, results_text, profit_text, perf_text)

    log(f"email_audit: subject='{subject}'")
    log(
        f"email_audit: sending to {cfg.email_recipient} "
        f"via {cfg.smtp_host}:{cfg.smtp_port}"
    )

    # --- Build MIME message -----------------------------------------------------
    msg = MIMEText(body, "plain", "utf-8")
    msg["Subject"] = subject
    msg["From"] = cfg.email_sender
    msg["To"] = cfg.email_recipient

    # --- Send via SMTP/TLS -------------------------------------------------------
    sent_flag = data_path(f"email_audit_sent_{date_str}.flag")

    try:
        with smtplib.SMTP(cfg.smtp_host, cfg.smtp_port, timeout=30) as smtp:
            smtp.ehlo()
            smtp.starttls()
            smtp.ehlo()
            smtp.login(cfg.email_sender, cfg.email_password)
            smtp.sendmail(cfg.email_sender, cfg.email_recipient, msg.as_string())
    except smtplib.SMTPException as exc:
        log(f"email_audit: SMTP error — {exc}", "ERROR")
        return 1
    except OSError as exc:
        log(f"email_audit: network/OS error — {exc}", "ERROR")
        return 1

    _write_flag(sent_flag)
    log("email_audit: evening audit email sent successfully")
    print(f"email_audit: SUCCESS — sent to {cfg.email_recipient}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
