"""
final_decision_guard.py — Final safety gate before email dispatch.

Loads final_nap_decision_YYYY-MM-DD.json and audits every condition
that could result in an unsafe or misleading bet recommendation reaching
the email recipient.

Checks performed:
  1. If status is BLOCKED or NO_BET: verify the text report contains
     no language implying an active bet.
  2. If status is CONFIRMED: verify the NAP horse is not flagged as
     NON_RUNNER and safe_to_bet is True.
  3. If safe_to_bet is False regardless of status: override any "bet"
     language to BLOCKED.

The text report is rewritten in-place if corrections are needed.
An audit log is always produced.

Inputs:
  data/final_nap_decision_YYYY-MM-DD.json

Outputs (always produced — never silently skipped):
  data/final_nap_decision_YYYY-MM-DD.json   (may be updated)
  reports/final_nap_decision_YYYY-MM-DD.txt (may be rewritten)
  reports/guard_audit_YYYY-MM-DD.txt        (audit log)

Exit codes:
  0 — all checks passed (or corrections applied successfully)
  1 — unrecoverable I/O error
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

from src.helpers import (
    data_path,
    log,
    report_path,
    safe_load_json,
    safe_write_json,
    today_str,
)


# ---------------------------------------------------------------------------
# Unsafe language patterns (case-insensitive substrings)
# ---------------------------------------------------------------------------

# Phrases that must NOT appear in BLOCKED/NO_BET reports
_BET_PHRASES: tuple[str, ...] = (
    "safe to bet: yes",
    "status: confirmed nap",
    "confirmed nap",
)

# Replacement text for overrides
_BLOCKED_OVERRIDE_REPORT = """\
═══════════════════════════════════════════════════════
  FINAL NAP DECISION — Safety Override
  Generated by final_decision_guard.py
═══════════════════════════════════════════════════════

STATUS: BLOCKED — Safe-to-bet flag was False

  ⚠ BLOCKED — guard override applied.
  No official bet today.

═══════════════════════════════════════════════════════
"""


# ---------------------------------------------------------------------------
# Audit log builder
# ---------------------------------------------------------------------------

class AuditLog:
    """Collects audit entries and writes a final report."""

    def __init__(self, date_str: str, generated_hm: str) -> None:
        self._date        = date_str
        self._generated   = generated_hm
        self._entries: list[str] = []
        self._corrections: list[str] = []

    def check(self, label: str, passed: bool, detail: str = "") -> None:
        """Record a single check result."""
        status = "PASS" if passed else "FAIL"
        msg = f"  [{status}] {label}"
        if detail:
            msg += f" — {detail}"
        self._entries.append(msg)
        log(f"guard_audit: [{status}] {label}{(' — ' + detail) if detail else ''}",
            "INFO" if passed else "WARNING")

    def correction(self, description: str) -> None:
        """Record a correction that was applied."""
        self._corrections.append(f"  [CORRECTED] {description}")
        log(f"guard_audit: CORRECTION APPLIED — {description}", "WARNING")

    def format(self) -> str:
        sep = "═" * 56
        lines: list[str] = [
            sep,
            "  FINAL DECISION GUARD — AUDIT LOG",
            f"  Date: {self._date}",
            f"  Generated: {self._generated}",
            sep,
            "",
            "■ CHECKS PERFORMED",
        ]
        lines.extend(self._entries)
        lines.append("")

        if self._corrections:
            lines.append("■ CORRECTIONS APPLIED")
            lines.extend(self._corrections)
        else:
            lines.append("■ CORRECTIONS APPLIED: None")

        lines.append("")
        overall = "CLEAN" if not self._corrections else "CORRECTED"
        lines.append(f"■ OVERALL RESULT: {overall}")
        lines.append("")
        lines.append(sep)

        return "\n".join(lines)

    @property
    def had_corrections(self) -> bool:
        return bool(self._corrections)


# ---------------------------------------------------------------------------
# Text report helpers
# ---------------------------------------------------------------------------

def _report_contains_bet_language(report_text: str) -> bool:
    """Return True if the report contains any unsafe bet-confirming phrase."""
    lower = report_text.lower()
    return any(phrase in lower for phrase in _BET_PHRASES)


def _read_report(report_path_str: str) -> str | None:
    """Read existing text report. Returns None on failure."""
    p = Path(report_path_str)
    if not p.exists():
        return None
    try:
        with open(p, "r", encoding="utf-8") as fh:
            return fh.read()
    except OSError as exc:
        log(f"guard: could not read report {report_path_str} — {exc}", "WARNING")
        return None


def _write_report(report_path_str: str, text: str) -> bool:
    """Write text report. Returns False on failure."""
    try:
        Path(report_path_str).parent.mkdir(parents=True, exist_ok=True)
        with open(report_path_str, "w", encoding="utf-8") as fh:
            fh.write(text)
        return True
    except OSError as exc:
        log(f"guard: failed to write report {report_path_str} — {exc}", "ERROR")
        return False


# ---------------------------------------------------------------------------
# Guard logic
# ---------------------------------------------------------------------------

def run_guard(
    decision: dict,
    report_text: str | None,
    audit: AuditLog,
) -> tuple[dict, str]:
    """
    Apply all safety checks to the decision dict and report text.

    Returns the (possibly modified) decision dict and (possibly rewritten)
    report text.
    """
    status     = str(decision.get("status") or "")
    safe_to_bet = bool(decision.get("safe_to_bet", False))
    nap_summary = decision.get("nap") or {}
    nap_status  = str(nap_summary.get("status") or "")

    report = report_text or ""

    # ------------------------------------------------------------------
    # Check 1: safe_to_bet coherence
    # ------------------------------------------------------------------
    stb_expected = (status == "CONFIRMED")
    stb_actual   = safe_to_bet

    audit.check(
        "safe_to_bet flag matches status",
        stb_expected == stb_actual,
        f"status={status} safe_to_bet={safe_to_bet}",
    )

    # If safe_to_bet is False but status says CONFIRMED — override everything
    if status == "CONFIRMED" and not safe_to_bet:
        audit.correction(
            "safe_to_bet=False but status=CONFIRMED — overriding to BLOCKED"
        )
        decision["status"]       = "BLOCKED"
        decision["block_reason"] = "Guard override: safe_to_bet was False"
        decision["safe_to_bet"]  = False
        status = "BLOCKED"

    # ------------------------------------------------------------------
    # Check 2: Non-runner in CONFIRMED state
    # ------------------------------------------------------------------
    if status == "CONFIRMED":
        nr_clean = nap_status != "NON_RUNNER"
        audit.check(
            "NAP is not flagged as non-runner",
            nr_clean,
            f"nap.status={nap_status}",
        )
        if not nr_clean:
            audit.correction(
                f"NAP flagged as NON_RUNNER but status=CONFIRMED — overriding to BLOCKED"
            )
            decision["status"]       = "BLOCKED"
            decision["block_reason"] = "Guard override: NAP is a non-runner"
            decision["safe_to_bet"]  = False
            status = "BLOCKED"

    # ------------------------------------------------------------------
    # Check 3: BLOCKED/NO_BET reports must not contain bet-confirming language
    # ------------------------------------------------------------------
    if status in ("BLOCKED", "NO_BET"):
        has_bet_language = _report_contains_bet_language(report)
        audit.check(
            f"Report ({status}) contains no bet-confirming language",
            not has_bet_language,
            "scanned for: " + ", ".join(f"'{p}'" for p in _BET_PHRASES),
        )
        if has_bet_language:
            audit.correction(
                f"Report contained bet-confirming language despite status={status} — "
                "replacing report with safe override"
            )
            # Build a clean override report
            block_reason = str(decision.get("block_reason") or status)
            report = (
                "═══════════════════════════════════════════════════════\n"
                "  FINAL NAP DECISION — Safety Override\n"
                "  Generated by final_decision_guard.py\n"
                "═══════════════════════════════════════════════════════\n"
                "\n"
                f"STATUS: {status}\n"
                "\n"
                f"  ⚠ {block_reason}\n"
                "  No official bet today.\n"
                "\n"
                "═══════════════════════════════════════════════════════\n"
            )

    # ------------------------------------------------------------------
    # Check 4: CONFIRMED reports must contain "safe to bet: yes"
    # ------------------------------------------------------------------
    if status == "CONFIRMED":
        has_safe_phrase = "safe to bet: yes" in report.lower()
        audit.check(
            "CONFIRMED report contains 'Safe to bet: YES'",
            has_safe_phrase,
        )
        # This is an informational check only — the report may use different
        # wording; we don't rewrite it here since CONFIRMED is already verified.

    # ------------------------------------------------------------------
    # Check 5: dangerous_drift never in a CONFIRMED decision
    # ------------------------------------------------------------------
    nap_warnings = decision.get("nap", {}) or {}
    if isinstance(nap_warnings, dict):
        nap_w_list = nap_warnings.get("warnings") or []
    else:
        nap_w_list = []

    # Also check decision-level warnings
    decision_warnings: list[str] = decision.get("warnings") or []
    has_drift = "dangerous_drift" in nap_w_list or "dangerous_drift" in decision_warnings

    if status == "CONFIRMED" and has_drift:
        audit.check(
            "CONFIRMED decision has no dangerous_drift warning",
            False,
            "dangerous_drift found — overriding to BLOCKED",
        )
        audit.correction(
            "dangerous_drift warning present in CONFIRMED decision — overriding to BLOCKED"
        )
        decision["status"]       = "BLOCKED"
        decision["block_reason"] = "Guard override: dangerous_drift flag detected"
        decision["safe_to_bet"]  = False
        status = "BLOCKED"
        report = (
            "═══════════════════════════════════════════════════════\n"
            "  FINAL NAP DECISION — Safety Override\n"
            "  Generated by final_decision_guard.py\n"
            "═══════════════════════════════════════════════════════\n"
            "\n"
            "STATUS: BLOCKED — Dangerous drift detected\n"
            "\n"
            "  ⚠ BLOCKED — dangerous_drift flag was present.\n"
            "  No official bet today.\n"
            "\n"
            "═══════════════════════════════════════════════════════\n"
        )
    else:
        audit.check(
            "No dangerous_drift in final decision",
            not has_drift,
            "clean" if not has_drift else "drift flag present (status already non-CONFIRMED)",
        )

    return decision, report


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    """Run final decision guard. Returns exit code."""
    log("final_decision_guard.py started")

    date_str     = today_str()
    now          = datetime.now(timezone.utc)
    generated_hm = now.strftime("%H:%M")

    audit = AuditLog(date_str, generated_hm)

    # ------------------------------------------------------------------
    # Load final_nap_decision JSON (required)
    # ------------------------------------------------------------------
    json_path = data_path(f"final_nap_decision_{date_str}.json")
    decision  = safe_load_json(json_path)

    if decision is None:
        audit.check(
            "final_nap_decision JSON loaded",
            False,
            f"File not found: {json_path}",
        )
        # Write audit log, then exit
        audit_text = audit.format()
        audit_dest = report_path(f"guard_audit_{date_str}.txt")
        _write_report(audit_dest, audit_text)
        log("final_decision_guard: final_nap_decision JSON not found — audit written",
            "ERROR")
        print(f"final_decision_guard: CRITICAL — decision file not found: {json_path}")
        return 1   # Genuine unrecoverable state (cannot produce a safe report)

    audit.check(
        "final_nap_decision JSON loaded",
        True,
        f"status={decision.get('status')}  safe_to_bet={decision.get('safe_to_bet')}",
    )

    # ------------------------------------------------------------------
    # Load existing text report (may be None if not yet written)
    # ------------------------------------------------------------------
    text_report_path_str = report_path(f"final_nap_decision_{date_str}.txt")
    existing_report      = _read_report(text_report_path_str)

    if existing_report is None:
        audit.check(
            "Text report file found",
            False,
            "Will be created fresh during guard pass",
        )
        existing_report = ""
    else:
        audit.check("Text report file found", True)

    # ------------------------------------------------------------------
    # Run guard checks
    # ------------------------------------------------------------------
    updated_decision, updated_report = run_guard(decision, existing_report, audit)

    # ------------------------------------------------------------------
    # Persist updated JSON if any corrections were made
    # ------------------------------------------------------------------
    if audit.had_corrections:
        if not safe_write_json(json_path, updated_decision):
            log("final_decision_guard: failed to write corrected JSON", "ERROR")
            # Write audit and return error
            _write_report(report_path(f"guard_audit_{date_str}.txt"), audit.format())
            return 1
        log(f"final_decision_guard: corrected JSON written → {json_path}")

        # Rewrite text report with corrected content
        if not _write_report(text_report_path_str, updated_report):
            log("final_decision_guard: failed to write corrected text report", "ERROR")
            _write_report(report_path(f"guard_audit_{date_str}.txt"), audit.format())
            return 1
        log(f"final_decision_guard: corrected text report written → {text_report_path_str}")

    elif not existing_report:
        # No corrections, but report was missing — write whatever we have
        if not _write_report(text_report_path_str, updated_report):
            log("final_decision_guard: failed to write missing text report", "ERROR")

    # ------------------------------------------------------------------
    # Write audit log (always)
    # ------------------------------------------------------------------
    audit_text = audit.format()
    audit_dest = report_path(f"guard_audit_{date_str}.txt")
    if not _write_report(audit_dest, audit_text):
        log(f"final_decision_guard: failed to write audit log — {audit_dest}", "ERROR")
        return 1
    log(f"final_decision_guard: audit log saved → {audit_dest}")

    # ------------------------------------------------------------------
    # Print summary
    # ------------------------------------------------------------------
    final_status = updated_decision.get("status", "UNKNOWN")
    if audit.had_corrections:
        print(
            f"final_decision_guard: CORRECTIONS APPLIED — "
            f"final status={final_status}  safe_to_bet={updated_decision.get('safe_to_bet')}"
        )
    else:
        print(
            f"final_decision_guard: ALL CHECKS PASSED — "
            f"status={final_status}  safe_to_bet={updated_decision.get('safe_to_bet')}"
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
