"""
hidden_signals_miner.py — Mine hidden predictive signals from cached backtest data.

Analyses data/backtest_cache/racecards/*.json cross-referenced with
data/backtest_cache/results/*.json (and data/backtest_cache/race_results/*.json)
to find untapped predictors that the current nap_selector_v3 model ignores.

Signals investigated:
  1. Draw bias (flat only) — by distance group and course
  2. Age patterns — win rate by age, age × class
  3. Sex / gender patterns — win rate and variance
  4. Weight carried — win rate by weight bracket
  5. Headgear first-time — vs second-time vs no headgear
  6. Wind surgery signal — is the +3pt bonus calibrated correctly?
  7. Spotlight / commentary NLP — positive vs negative keyword win rates
  8. Trainer × jockey combination — "hot hands" combos
  9. Quick return (flat vs jumps split) — evidence for the pending fix

Outputs:
  reports/hidden_signals_{date_str}.txt
  data/hidden_signals_{date_str}.json

Usage:
  python hidden_signals_miner.py
  python hidden_signals_miner.py --cache-dir /custom/path

Exit codes:
  0 — report produced (even if no cached data — writes structure and notes)
  1 — fatal write error
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Path helpers (mirror src/helpers.py without importing it — avoids config dep)
# ---------------------------------------------------------------------------

def _project_dir() -> Path:
    """Return the project root directory."""
    return Path(__file__).parent


def _data_path(filename: str) -> Path:
    p = _project_dir() / "data" / filename
    p.parent.mkdir(parents=True, exist_ok=True)
    return p


def _report_path(filename: str) -> Path:
    p = _project_dir() / "reports" / filename
    p.parent.mkdir(parents=True, exist_ok=True)
    return p


def _cache_dir(base: Optional[str] = None) -> Path:
    if base:
        return Path(base)
    return _project_dir() / "data" / "backtest_cache"


# ---------------------------------------------------------------------------
# Safe value helpers
# ---------------------------------------------------------------------------

def _safe_int(val, default: int = -1) -> int:
    try:
        return int(val)
    except (TypeError, ValueError):
        return default


def _safe_float(val, default: float = 0.0) -> float:
    try:
        return float(val)
    except (TypeError, ValueError):
        return default


def _safe_str(val, default: str = "") -> str:
    if val is None:
        return default
    return str(val).strip()


# ---------------------------------------------------------------------------
# Cache loaders
# ---------------------------------------------------------------------------

def _load_json(path: Path) -> Optional[dict]:
    if not path.exists():
        return None
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, json.JSONDecodeError):
        return None


def load_all_racecards(cache_base: Path) -> list[dict]:
    """
    Load all racecard files from cache_base/racecards/*.json.
    Each file has structure: {"races": [ {race_dict}, ... ]}
    Returns a flat list of race dicts (each with a "runners" list).
    """
    rc_dir = cache_base / "racecards"
    if not rc_dir.exists():
        return []

    all_races: list[dict] = []
    for f in sorted(rc_dir.glob("*.json")):
        data = _load_json(f)
        if not data:
            continue
        races = data.get("races") or []
        for race in races:
            race["_source_file"] = f.stem   # date string for debug
            all_races.append(race)
    return all_races


def load_results_lookup(cache_base: Path) -> dict[str, dict]:
    """
    Build a horse_id → {position, sp_dec} lookup from all cached race results.
    Checks two cache locations:
      - cache_base/race_results/<race_id>.json  {"runners": {horse_id: {pos, sp}}}
      - cache_base/results/<date>.json          (legacy daily format)
    """
    lookup: dict[str, dict] = {}

    # Per-race results cache (preferred — generated by historical_backtest.py)
    rr_dir = cache_base / "race_results"
    if rr_dir.exists():
        for f in sorted(rr_dir.glob("*.json")):
            data = _load_json(f)
            if not data:
                continue
            runners = data.get("runners") or {}
            for hid, rdata in runners.items():
                if hid and hid not in lookup:
                    lookup[hid] = rdata

    # Legacy daily results cache (fallback)
    res_dir = cache_base / "results"
    if res_dir.exists():
        for f in sorted(res_dir.glob("*.json")):
            data = _load_json(f)
            if not data:
                continue
            # Support multiple possible shapes
            runners_raw = (
                data.get("runners")
                or data.get("results")
                or []
            )
            if isinstance(runners_raw, list):
                for r in runners_raw:
                    hid = _safe_str(r.get("horse_id"))
                    pos = _safe_str(r.get("position") or r.get("finish_position"))
                    sp = _safe_float(r.get("sp_dec") or r.get("bsp") or r.get("sp"))
                    if hid and hid not in lookup:
                        lookup[hid] = {"position": pos, "sp_dec": sp}
            elif isinstance(runners_raw, dict):
                for hid, rdata in runners_raw.items():
                    if hid and hid not in lookup:
                        lookup[hid] = rdata

    return lookup


# ---------------------------------------------------------------------------
# Race-type helpers
# ---------------------------------------------------------------------------

def _is_flat(race: dict) -> bool:
    rt = _safe_str(race.get("type")).lower()
    return not any(x in rt for x in ("chase", "hurdle", "bumper", "nhf"))


def _is_jump(race: dict) -> bool:
    rt = _safe_str(race.get("type")).lower()
    return any(x in rt for x in ("chase", "hurdle", "bumper", "nhf"))


def _dist_group(f: float) -> str:
    if f <= 0:
        return "Unknown"
    if f < 7.0:
        return "Sprint (<7f)"
    if f < 10.5:
        return "Mile (7-10.5f)"
    if f < 14.0:
        return "Middle (10.5-14f)"
    return "Staying (14f+)"


def _dist_label_short(f: float) -> str:
    if f <= 0:
        return "?"
    if f < 7.0:
        return "sprint"
    if f < 10.5:
        return "mile"
    return "staying"


# ---------------------------------------------------------------------------
# Stats containers
# ---------------------------------------------------------------------------

class WinStats:
    """Accumulate wins / runs / variance for a categorical group."""

    __slots__ = ("runs", "wins", "places", "sp_sum", "sp_sq_sum")

    def __init__(self):
        self.runs = 0
        self.wins = 0
        self.places = 0    # top-3 finishes
        self.sp_sum = 0.0
        self.sp_sq_sum = 0.0

    def record(self, won: bool, placed: bool, sp: float = 0.0):
        self.runs += 1
        if won:
            self.wins += 1
        if placed:
            self.places += 1
        if sp > 1.0:
            self.sp_sum += sp
            self.sp_sq_sum += sp * sp

    @property
    def win_pct(self) -> float:
        return self.wins / self.runs * 100.0 if self.runs else 0.0

    @property
    def place_pct(self) -> float:
        return self.places / self.runs * 100.0 if self.runs else 0.0

    def to_dict(self) -> dict:
        return {
            "runs": self.runs,
            "wins": self.wins,
            "places": self.places,
            "win_pct": round(self.win_pct, 2),
            "place_pct": round(self.place_pct, 2),
        }


def _get_position(runner: dict, result_lookup: dict) -> tuple[int, float]:
    """Return (position_int, sp_dec) for a runner. 99 means unknown/unplaced."""
    hid = _safe_str(runner.get("horse_id"))
    # Check racecard-embedded position first (some API configs embed it)
    pos_raw = _safe_str(runner.get("position"))
    sp_raw = _safe_float(runner.get("sp_dec"))
    if not pos_raw and hid and hid in result_lookup:
        rd = result_lookup[hid]
        pos_raw = _safe_str(rd.get("position"))
        sp_raw = _safe_float(rd.get("sp_dec"))
    try:
        pos_int = int(pos_raw)
    except (ValueError, TypeError):
        pos_int = 99
    return pos_int, sp_raw


# ---------------------------------------------------------------------------
# SIGNAL 1: DRAW ANALYSIS
# ---------------------------------------------------------------------------

def analyse_draw(all_races: list[dict], result_lookup: dict) -> dict:
    """
    Flat races only.
    For each runner: record draw, normalised draw, distance group, course.
    Compute win rates for low/mid/high draw thirds by distance group.
    Also compute per-course draw bias (courses with 10+ flat races).
    """
    # dist_group -> draw_third ("low"/"mid"/"high") -> WinStats
    by_dist_draw: dict[str, dict[str, WinStats]] = defaultdict(
        lambda: {"low": WinStats(), "mid": WinStats(), "high": WinStats()}
    )
    # course -> draw_third -> WinStats
    by_course_draw: dict[str, dict[str, WinStats]] = defaultdict(
        lambda: {"low": WinStats(), "mid": WinStats(), "high": WinStats()}
    )
    # raw draw number -> WinStats (sprint flat only, pooled)
    draw_number_sprint: dict[int, WinStats] = defaultdict(WinStats)

    races_processed = 0
    runners_processed = 0
    races_with_draw = 0

    for race in all_races:
        if not _is_flat(race):
            continue
        dist_f = _safe_float(race.get("distance_f"))
        course = _safe_str(race.get("course"))
        runners = race.get("runners") or []
        field_size = max(_safe_int(race.get("field_size"), default=len(runners)), len(runners))
        if field_size < 3:
            continue

        # Check whether draw data is present at all
        draws = [_safe_int(r.get("draw"), default=-1) for r in runners]
        valid_draws = [d for d in draws if d > 0]
        if not valid_draws:
            continue

        races_with_draw += 1
        races_processed += 1
        dist_grp = _dist_group(dist_f)

        for runner in runners:
            draw_val = _safe_int(runner.get("draw"), default=-1)
            if draw_val <= 0:
                continue
            pos_int, sp = _get_position(runner, result_lookup)
            if pos_int == 99:
                continue   # no result — skip

            won = pos_int == 1
            placed = pos_int <= 3

            # Normalised draw: 0.0 (lowest) to 1.0 (highest)
            norm_draw = (draw_val - 1) / max(field_size - 1, 1)
            if norm_draw < 0.333:
                draw_third = "low"
            elif norm_draw < 0.667:
                draw_third = "mid"
            else:
                draw_third = "high"

            by_dist_draw[dist_grp][draw_third].record(won, placed, sp)
            by_course_draw[course][draw_third].record(won, placed, sp)
            runners_processed += 1

            if dist_f < 7.0:
                draw_number_sprint[draw_val].record(won, placed, sp)

    # --- Compute bias scores per course ---
    # Bias = |low_win_pct - high_win_pct|, only where each cell has >= 5 runs
    course_bias: list[tuple[str, float, str, dict]] = []
    for course, thirds in by_course_draw.items():
        low_s = thirds["low"]
        high_s = thirds["high"]
        total_runs = sum(t.runs for t in thirds.values())
        if total_runs < 20:
            continue
        if low_s.runs < 5 or high_s.runs < 5:
            continue
        bias = low_s.win_pct - high_s.win_pct
        direction = "LOW_DRAW_FAVOURED" if bias > 0 else "HIGH_DRAW_FAVOURED"
        course_bias.append((
            course,
            abs(bias),
            direction,
            {
                "low_runs": low_s.runs, "low_win_pct": round(low_s.win_pct, 1),
                "mid_runs": thirds["mid"].runs, "mid_win_pct": round(thirds["mid"].win_pct, 1),
                "high_runs": high_s.runs, "high_win_pct": round(high_s.win_pct, 1),
                "bias_pct": round(bias, 1),
            }
        ))
    course_bias.sort(key=lambda x: x[1], reverse=True)
    top_courses = course_bias[:5]

    # --- Build distance summary ---
    dist_summary: dict[str, dict] = {}
    for dist_grp, thirds in by_dist_draw.items():
        dist_summary[dist_grp] = {
            third: thirds[third].to_dict() for third in ("low", "mid", "high")
        }

    # --- Sprint stall analysis (top 10 stalls by win %) ---
    sprint_stalls = []
    for stall, stats in sorted(draw_number_sprint.items()):
        if stats.runs >= 5:
            sprint_stalls.append({
                "stall": stall,
                "runs": stats.runs,
                "wins": stats.wins,
                "win_pct": round(stats.win_pct, 1),
            })
    sprint_stalls.sort(key=lambda x: x["win_pct"], reverse=True)

    return {
        "races_with_flat_draw_data": races_with_draw,
        "runners_analysed": runners_processed,
        "by_distance_group": dist_summary,
        "top_5_biased_courses": [
            {
                "course": c,
                "bias_magnitude_pct": round(b, 1),
                "direction": d,
                **data,
            }
            for c, b, d, data in top_courses
        ],
        "sprint_stall_win_rates": sprint_stalls[:15],
    }


# ---------------------------------------------------------------------------
# SIGNAL 2: AGE PATTERNS
# ---------------------------------------------------------------------------

def _age_bucket(age_str: str) -> str:
    try:
        age = int(age_str.strip())
    except (ValueError, TypeError, AttributeError):
        return "Unknown"
    if age == 2:
        return "2yo"
    if age == 3:
        return "3yo"
    if age == 4:
        return "4yo"
    if age == 5:
        return "5yo"
    if age == 6:
        return "6yo"
    return "7yo+"


def _class_bucket(race_class) -> str:
    if race_class is None:
        return "Unknown"
    s = str(race_class).strip().lower()
    if s.startswith("class"):
        s = s[5:].strip()
    if "grade 1" in s or "listed" in s:
        return "Elite"
    if "grade" in s:
        return "Graded"
    try:
        c = int(s)
        if c <= 2:
            return "Class1-2"
        if c <= 4:
            return "Class3-4"
        return "Class5+"
    except (TypeError, ValueError):
        return "Unknown"


def analyse_age(all_races: list[dict], result_lookup: dict) -> dict:
    by_age: dict[str, WinStats] = defaultdict(WinStats)
    # age_bucket × class_bucket
    by_age_class: dict[str, dict[str, WinStats]] = defaultdict(lambda: defaultdict(WinStats))
    # variance: track positions to compute std dev
    age_positions: dict[str, list[int]] = defaultdict(list)

    for race in all_races:
        race_class = race.get("class")
        cls_bkt = _class_bucket(race_class)
        for runner in (race.get("runners") or []):
            age_bkt = _age_bucket(_safe_str(runner.get("age")))
            pos_int, sp = _get_position(runner, result_lookup)
            if pos_int == 99:
                continue
            won = pos_int == 1
            placed = pos_int <= 3
            by_age[age_bkt].record(won, placed, sp)
            by_age_class[age_bkt][cls_bkt].record(won, placed, sp)
            if pos_int < 20:
                age_positions[age_bkt].append(pos_int)

    # Variance proxy: std dev of finishing positions
    age_variance: dict[str, float] = {}
    for bkt, positions in age_positions.items():
        if len(positions) >= 5:
            mean = sum(positions) / len(positions)
            variance = sum((p - mean) ** 2 for p in positions) / len(positions)
            age_variance[bkt] = round(variance ** 0.5, 2)

    age_summary: dict[str, dict] = {}
    for bkt in ("2yo", "3yo", "4yo", "5yo", "6yo", "7yo+", "Unknown"):
        if bkt in by_age and by_age[bkt].runs > 0:
            d = by_age[bkt].to_dict()
            d["position_std_dev"] = age_variance.get(bkt)
            age_summary[bkt] = d

    # Cross-tab: age × class
    age_class_table: dict[str, dict] = {}
    for age_bkt, class_dict in by_age_class.items():
        age_class_table[age_bkt] = {
            cls: stats.to_dict()
            for cls, stats in class_dict.items()
            if stats.runs >= 5
        }

    return {
        "by_age": age_summary,
        "age_position_variance": age_variance,
        "age_class_crosstab": age_class_table,
    }


# ---------------------------------------------------------------------------
# SIGNAL 3: SEX / GENDER PATTERNS
# ---------------------------------------------------------------------------

def _sex_bucket(sex_str: str) -> str:
    s = sex_str.strip().lower()
    if s in ("g", "gelding"):
        return "Gelding"
    if s in ("c", "colt"):
        return "Colt"
    if s in ("f", "filly"):
        return "Filly"
    if s in ("m", "mare"):
        return "Mare"
    if s in ("h", "horse"):
        return "Horse (entire)"
    if s in ("r", "rig"):
        return "Rig"
    return f"Other({sex_str})" if sex_str else "Unknown"


def analyse_sex(all_races: list[dict], result_lookup: dict) -> dict:
    by_sex: dict[str, WinStats] = defaultdict(WinStats)
    by_sex_class: dict[str, dict[str, WinStats]] = defaultdict(lambda: defaultdict(WinStats))
    sex_positions: dict[str, list[int]] = defaultdict(list)

    for race in all_races:
        cls_bkt = _class_bucket(race.get("class"))
        for runner in (race.get("runners") or []):
            sex_bkt = _sex_bucket(_safe_str(runner.get("sex")))
            pos_int, sp = _get_position(runner, result_lookup)
            if pos_int == 99:
                continue
            won = pos_int == 1
            placed = pos_int <= 3
            by_sex[sex_bkt].record(won, placed, sp)
            by_sex_class[sex_bkt][cls_bkt].record(won, placed, sp)
            if pos_int < 20:
                sex_positions[sex_bkt].append(pos_int)

    sex_variance: dict[str, float] = {}
    for bkt, positions in sex_positions.items():
        if len(positions) >= 5:
            mean = sum(positions) / len(positions)
            var = sum((p - mean) ** 2 for p in positions) / len(positions)
            sex_variance[bkt] = round(var ** 0.5, 2)

    sex_summary: dict[str, dict] = {}
    for bkt, stats in by_sex.items():
        if stats.runs >= 5:
            d = stats.to_dict()
            d["position_std_dev"] = sex_variance.get(bkt)
            sex_summary[bkt] = d

    sex_class_table: dict[str, dict] = {}
    for sex_bkt, class_dict in by_sex_class.items():
        sex_class_table[sex_bkt] = {
            cls: stats.to_dict()
            for cls, stats in class_dict.items()
            if stats.runs >= 5
        }

    return {
        "by_sex": sex_summary,
        "sex_position_variance": sex_variance,
        "sex_class_crosstab": sex_class_table,
    }


# ---------------------------------------------------------------------------
# SIGNAL 4: WEIGHT CARRIED
# ---------------------------------------------------------------------------

def _weight_bucket(lbs: int) -> str:
    """
    Typical racing weights:
      126 lbs = 9-0  (9 stone)
      133 lbs = 9-7
      126 = 9-0, 119 = 8-7, 112 = 8-0 (rarely seen)
    Common spread: 118–135 lbs
    """
    if lbs <= 0:
        return "Unknown"
    if lbs < 119:
        return "<8-7 (featherweight)"
    if lbs < 126:
        return "8-7 to 8-13"
    if lbs < 133:
        return "9-0 to 9-6"
    if lbs < 140:
        return "9-7 to 9-13"
    return "10-0+ (topweight)"


def analyse_weight(all_races: list[dict], result_lookup: dict) -> dict:
    by_weight: dict[str, WinStats] = defaultdict(WinStats)
    # flat vs jump split
    by_weight_type: dict[str, dict[str, WinStats]] = defaultdict(lambda: defaultdict(WinStats))

    for race in all_races:
        race_type_tag = "flat" if _is_flat(race) else "jump"
        for runner in (race.get("runners") or []):
            # Prefer weight_lbs; fall back to lbs
            lbs = _safe_int(runner.get("weight_lbs"), default=-1)
            if lbs <= 0:
                lbs = _safe_int(runner.get("lbs"), default=-1)
            wt_bkt = _weight_bucket(lbs)
            pos_int, sp = _get_position(runner, result_lookup)
            if pos_int == 99:
                continue
            won = pos_int == 1
            placed = pos_int <= 3
            by_weight[wt_bkt].record(won, placed, sp)
            by_weight_type[wt_bkt][race_type_tag].record(won, placed, sp)

    weight_summary: dict[str, dict] = {
        bkt: stats.to_dict()
        for bkt, stats in by_weight.items()
        if stats.runs >= 5
    }
    weight_by_type: dict[str, dict] = {
        bkt: {
            t: s.to_dict() for t, s in type_dict.items() if s.runs >= 5
        }
        for bkt, type_dict in by_weight_type.items()
        if sum(s.runs for s in type_dict.values()) >= 5
    }

    # Find sweet spot: bucket with highest win_pct among those with >= 20 runs
    sweet_spot = None
    best_pct = 0.0
    for bkt, stats in by_weight.items():
        if stats.runs >= 20 and stats.win_pct > best_pct:
            best_pct = stats.win_pct
            sweet_spot = bkt

    return {
        "by_weight_bracket": weight_summary,
        "by_weight_and_type": weight_by_type,
        "sweet_spot_bracket": sweet_spot,
        "sweet_spot_win_pct": round(best_pct, 1) if sweet_spot else None,
    }


# ---------------------------------------------------------------------------
# SIGNAL 5: HEADGEAR FIRST-TIME ANALYSIS
# ---------------------------------------------------------------------------

def analyse_headgear(all_races: list[dict], result_lookup: dict) -> dict:
    """
    headgear_run == 1  → first time wearing headgear
    headgear_run == 2  → second time
    headgear_run == 0 or -1 → not wearing / unknown
    headgear_run > 2   → established (2+)
    """
    # headgear_status ("none", "first", "second", "established") -> WinStats
    by_hg_status: dict[str, WinStats] = defaultdict(WinStats)
    # headgear type (blinkers / visor / hood etc) for first-time only
    by_hg_type_first: dict[str, WinStats] = defaultdict(WinStats)
    # flat vs jump for first-time
    first_time_by_type: dict[str, WinStats] = defaultdict(WinStats)

    total_runners_with_result = 0

    for race in all_races:
        race_type_tag = "flat" if _is_flat(race) else "jump"
        for runner in (race.get("runners") or []):
            pos_int, sp = _get_position(runner, result_lookup)
            if pos_int == 99:
                continue
            total_runners_with_result += 1

            won = pos_int == 1
            placed = pos_int <= 3
            hg_run = _safe_int(runner.get("headgear_run"), default=-1)
            hg_type = _safe_str(runner.get("headgear")).lower() or "none"

            if hg_run == 1:
                hg_status = "first_time"
                by_hg_type_first[hg_type].record(won, placed, sp)
                first_time_by_type[race_type_tag].record(won, placed, sp)
            elif hg_run == 2:
                hg_status = "second_time"
            elif hg_run >= 3:
                hg_status = "established"
            else:
                hg_status = "no_headgear"

            by_hg_status[hg_status].record(won, placed, sp)

    headgear_summary: dict[str, dict] = {
        status: stats.to_dict()
        for status, stats in by_hg_status.items()
        if stats.runs >= 3
    }
    # Baseline = no headgear win %
    baseline_pct = by_hg_status["no_headgear"].win_pct if by_hg_status["no_headgear"].runs >= 10 else None

    first_time_pct = by_hg_status["first_time"].win_pct if by_hg_status["first_time"].runs >= 5 else None
    delta = None
    if baseline_pct is not None and first_time_pct is not None:
        delta = round(first_time_pct - baseline_pct, 2)

    by_hg_type_summary: dict[str, dict] = {
        t: s.to_dict()
        for t, s in by_hg_type_first.items()
        if s.runs >= 3
    }

    first_time_by_race: dict[str, dict] = {
        t: s.to_dict()
        for t, s in first_time_by_type.items()
        if s.runs >= 3
    }

    return {
        "by_headgear_status": headgear_summary,
        "baseline_no_headgear_win_pct": round(baseline_pct, 2) if baseline_pct else None,
        "first_time_win_pct": round(first_time_pct, 2) if first_time_pct else None,
        "first_time_vs_baseline_delta": delta,
        "first_time_by_headgear_type": by_hg_type_summary,
        "first_time_by_race_type": first_time_by_race,
    }


# ---------------------------------------------------------------------------
# SIGNAL 6: WIND SURGERY SIGNAL
# ---------------------------------------------------------------------------

def analyse_wind_surgery(all_races: list[dict], result_lookup: dict) -> dict:
    """
    wind_surgery_run == 1 → first run after wind surgery
    Compare win rate vs baseline (no wind surgery).
    Current model gives +3pts for wind_surgery_run == 1.
    """
    first_run_stats = WinStats()
    established_stats = WinStats()   # wind_surgery_run >= 2
    no_surgery_stats = WinStats()
    surgery_unknown_stats = WinStats()

    # Also split by flat/jump
    first_run_flat = WinStats()
    first_run_jump = WinStats()

    for race in all_races:
        is_f = _is_flat(race)
        for runner in (race.get("runners") or []):
            pos_int, sp = _get_position(runner, result_lookup)
            if pos_int == 99:
                continue
            won = pos_int == 1
            placed = pos_int <= 3
            ws_run = _safe_int(runner.get("wind_surgery_run"), default=-1)

            if ws_run == 1:
                first_run_stats.record(won, placed, sp)
                if is_f:
                    first_run_flat.record(won, placed, sp)
                else:
                    first_run_jump.record(won, placed, sp)
            elif ws_run >= 2:
                established_stats.record(won, placed, sp)
            elif ws_run == 0:
                no_surgery_stats.record(won, placed, sp)
            else:
                surgery_unknown_stats.record(won, placed, sp)

    baseline_pct = None
    first_pct = None
    if no_surgery_stats.runs >= 20:
        baseline_pct = round(no_surgery_stats.win_pct, 2)
    if first_run_stats.runs >= 5:
        first_pct = round(first_run_stats.win_pct, 2)

    # Calibration: is +3pts justified?
    # +3pts on a 100pt scale ≈ 3% score boost. Meaningful if win rate is
    # notably above baseline.
    calibration_note = "insufficient data"
    if baseline_pct is not None and first_pct is not None:
        delta = first_pct - baseline_pct
        if delta >= 5.0:
            calibration_note = f"+3pts may be UNDER-valued (actual edge +{delta:.1f}%)"
        elif delta >= 2.0:
            calibration_note = f"+3pts appropriate (actual edge +{delta:.1f}%)"
        elif delta >= 0:
            calibration_note = f"+3pts generous (actual edge only +{delta:.1f}%)"
        else:
            calibration_note = f"+3pts NOT JUSTIFIED — wind surgery horses win LESS often ({delta:.1f}%)"

    return {
        "first_run_after_surgery": first_run_stats.to_dict(),
        "first_run_flat": first_run_flat.to_dict(),
        "first_run_jump": first_run_jump.to_dict(),
        "established_surgery": established_stats.to_dict(),
        "no_surgery_baseline": no_surgery_stats.to_dict(),
        "baseline_win_pct": baseline_pct,
        "first_run_win_pct": first_pct,
        "calibration_note": calibration_note,
    }


# ---------------------------------------------------------------------------
# SIGNAL 7: SPOTLIGHT / COMMENTARY NLP
# ---------------------------------------------------------------------------

# Positive signals — suggest trainer confidence, horse in good form
_POSITIVE_KEYWORDS = [
    "improves", "progressive", "well held", "going well",
    "fit", "interesting", "danger", "danger here", "chance",
    "could go well", "capable", "promising", "exciting",
    "big run", "bold bid", "right in contention",
    "fancied", "market confident", "ready",
]

# Negative signals — suggest excuses or decline
_NEGATIVE_KEYWORDS = [
    "disappointing", "beaten favourite", "struggle", "needs",
    "below par", "below form", "out of form", "not beaten far",
    "hard to fancy", "hard to see", "looks held", "beaten easily",
    "unproven", "worried", "poor effort", "well beaten",
    "not for us", "avoid", "too big an ask", "tough task",
]

# Strong positive phrases from stable tours / quotes
_STRONG_POSITIVE = [
    "should win", "win this", "expected to win", "strong fancy",
    "love this horse", "very well", "highly tried",
    "excited about", "best performance",
]

# Strong negative phrases
_STRONG_NEGATIVE = [
    "not entered by mistake", "needs a break", "not right",
    "gallop a concern", "lame", "injury",
]


def _score_text(text: str) -> tuple[int, list[str]]:
    """
    Return (sentiment_score, matched_keywords).
    Positive match = +1, negative match = -1, strong +/- = ±2.
    """
    if not text:
        return 0, []
    t = text.lower()
    score = 0
    matched: list[str] = []
    for kw in _STRONG_POSITIVE:
        if kw in t:
            score += 2
            matched.append(f"+2:{kw}")
    for kw in _STRONG_NEGATIVE:
        if kw in t:
            score -= 2
            matched.append(f"-2:{kw}")
    for kw in _POSITIVE_KEYWORDS:
        if kw in t and f"+2:{kw}" not in matched:
            score += 1
            matched.append(f"+1:{kw}")
    for kw in _NEGATIVE_KEYWORDS:
        if kw in t and f"-2:{kw}" not in matched:
            score -= 1
            matched.append(f"-1:{kw}")
    return score, matched


def analyse_commentary(all_races: list[dict], result_lookup: dict) -> dict:
    # sentiment_bucket ("strong_pos", "mild_pos", "neutral", "mild_neg", "strong_neg")
    sentiment_stats: dict[str, WinStats] = defaultdict(WinStats)
    # keyword -> WinStats (for individual keyword alpha)
    keyword_stats: dict[str, WinStats] = defaultdict(WinStats)

    field_count = 0
    any_text_count = 0

    for race in all_races:
        for runner in (race.get("runners") or []):
            pos_int, sp = _get_position(runner, result_lookup)
            if pos_int == 99:
                continue
            field_count += 1
            won = pos_int == 1
            placed = pos_int <= 3

            # Combine all commentary fields
            text_parts = [
                _safe_str(runner.get("spotlight")),
                _safe_str(runner.get("comment")),
                _safe_str(runner.get("quotes")),
                _safe_str(runner.get("stable_tour")),
            ]
            combined_text = " ".join(p for p in text_parts if p)

            if not combined_text:
                sentiment_stats["no_commentary"].record(won, placed, sp)
                continue

            any_text_count += 1
            sent_score, matched_kws = _score_text(combined_text)

            if sent_score >= 3:
                bucket = "strong_positive"
            elif sent_score >= 1:
                bucket = "mild_positive"
            elif sent_score <= -3:
                bucket = "strong_negative"
            elif sent_score <= -1:
                bucket = "mild_negative"
            else:
                bucket = "neutral"

            sentiment_stats[bucket].record(won, placed, sp)

            # Per-keyword stats
            for kw_label in matched_kws:
                keyword_stats[kw_label].record(won, placed, sp)

    # Find high-alpha keywords (win rate vs baseline, min 10 occurrences)
    baseline_pct = None
    if sentiment_stats["neutral"].runs >= 10:
        baseline_pct = sentiment_stats["neutral"].win_pct

    high_alpha_keywords: list[dict] = []
    for kw, stats in keyword_stats.items():
        if stats.runs >= 10 and baseline_pct is not None:
            delta = stats.win_pct - baseline_pct
            high_alpha_keywords.append({
                "keyword": kw,
                "runs": stats.runs,
                "wins": stats.wins,
                "win_pct": round(stats.win_pct, 1),
                "vs_baseline": round(delta, 1),
            })
    high_alpha_keywords.sort(key=lambda x: x["vs_baseline"], reverse=True)

    return {
        "runners_with_result": field_count,
        "runners_with_commentary": any_text_count,
        "commentary_coverage_pct": round(any_text_count / field_count * 100, 1) if field_count else 0.0,
        "by_sentiment": {
            bucket: stats.to_dict()
            for bucket, stats in sentiment_stats.items()
            if stats.runs >= 3
        },
        "high_alpha_keywords": high_alpha_keywords[:20],
        "baseline_neutral_win_pct": round(baseline_pct, 2) if baseline_pct else None,
    }


# ---------------------------------------------------------------------------
# SIGNAL 8: TRAINER × JOCKEY COMBINATION
# ---------------------------------------------------------------------------

def analyse_trainer_jockey(all_races: list[dict], result_lookup: dict) -> dict:
    combo_stats: dict[str, WinStats] = defaultdict(WinStats)
    trainer_stats: dict[str, WinStats] = defaultdict(WinStats)
    jockey_stats: dict[str, WinStats] = defaultdict(WinStats)

    for race in all_races:
        for runner in (race.get("runners") or []):
            pos_int, sp = _get_position(runner, result_lookup)
            if pos_int == 99:
                continue
            won = pos_int == 1
            placed = pos_int <= 3
            trainer = _safe_str(runner.get("trainer"))
            jockey = _safe_str(runner.get("jockey"))

            if trainer:
                trainer_stats[trainer].record(won, placed, sp)
            if jockey:
                jockey_stats[jockey].record(won, placed, sp)
            if trainer and jockey:
                combo_key = f"{trainer} / {jockey}"
                combo_stats[combo_key].record(won, placed, sp)

    # Filter combos with >= 5 runs
    qualified_combos = [
        (combo, stats)
        for combo, stats in combo_stats.items()
        if stats.runs >= 5
    ]
    qualified_combos.sort(key=lambda x: x[1].win_pct, reverse=True)

    top_combos: list[dict] = []
    for combo, stats in qualified_combos[:20]:
        trainer, jockey = combo.split(" / ", 1) if " / " in combo else (combo, "")
        # Marginal edge = combo win% - (trainer_win% + jockey_win%) / 2
        t_pct = trainer_stats[trainer].win_pct if trainer and trainer_stats[trainer].runs >= 5 else None
        j_pct = jockey_stats[jockey].win_pct if jockey and jockey_stats[jockey].runs >= 5 else None
        if t_pct is not None and j_pct is not None:
            expected = (t_pct + j_pct) / 2
            edge = round(stats.win_pct - expected, 1)
        else:
            edge = None
        top_combos.append({
            "combo": combo,
            "runs": stats.runs,
            "wins": stats.wins,
            "win_pct": round(stats.win_pct, 1),
            "place_pct": round(stats.place_pct, 1),
            "trainer_solo_win_pct": round(t_pct, 1) if t_pct else None,
            "jockey_solo_win_pct": round(j_pct, 1) if j_pct else None,
            "combo_edge_over_solo_avg": edge,
        })

    # Top 10 trainers and jockeys by win %
    top_trainers = sorted(
        [(t, s) for t, s in trainer_stats.items() if s.runs >= 10],
        key=lambda x: x[1].win_pct, reverse=True
    )[:10]
    top_jockeys = sorted(
        [(j, s) for j, s in jockey_stats.items() if s.runs >= 10],
        key=lambda x: x[1].win_pct, reverse=True
    )[:10]

    return {
        "total_trainer_jockey_combos_with_5plus_runs": len(qualified_combos),
        "top_10_hot_hands_combos": top_combos[:10],
        "top_10_trainers_by_win_pct": [
            {"trainer": t, **s.to_dict()} for t, s in top_trainers
        ],
        "top_10_jockeys_by_win_pct": [
            {"jockey": j, **s.to_dict()} for j, s in top_jockeys
        ],
        "model_gap_note": (
            "Current model accounts for trainer 14-day form (0-15pts) "
            "but NOT for jockey or trainer×jockey combination. "
            "Adding combo bonus of +2 to +5pts for top combos could improve selection."
        ),
    }


# ---------------------------------------------------------------------------
# SIGNAL 9: QUICK RETURN — FLAT vs JUMPS SPLIT
# ---------------------------------------------------------------------------

def analyse_quick_return(all_races: list[dict], result_lookup: dict) -> dict:
    """
    last_run days → win rate for flat vs jump races.
    Current model: applies same freshness bonus regardless of race type.
    Hypothesis: quick return (<7 days) helps flat horses but not jump horses.
    """
    # type_tag -> days_bucket -> WinStats
    by_type_return: dict[str, dict[str, WinStats]] = {
        "flat": defaultdict(WinStats),
        "jump": defaultdict(WinStats),
    }

    def _days_bucket(days: int) -> str:
        if days < 0:
            return "unknown"
        if days < 7:
            return "<7_days"
        if days < 14:
            return "7-13_days"
        if days < 28:
            return "14-27_days"
        if days < 45:
            return "28-44_days"
        if days < 70:
            return "45-69_days"
        return "70+_days"

    for race in all_races:
        type_tag = "flat" if _is_flat(race) else "jump"
        for runner in (race.get("runners") or []):
            pos_int, sp = _get_position(runner, result_lookup)
            if pos_int == 99:
                continue
            last_run = _safe_int(runner.get("last_run"), default=-1)
            days_bkt = _days_bucket(last_run)
            won = pos_int == 1
            placed = pos_int <= 3
            by_type_return[type_tag][days_bkt].record(won, placed, sp)

    result: dict[str, dict] = {}
    for type_tag, bucket_dict in by_type_return.items():
        result[type_tag] = {
            bkt: stats.to_dict()
            for bkt, stats in bucket_dict.items()
            if stats.runs >= 5
        }

    # Key comparison: quick return (<7 days) flat vs jump
    flat_quick = by_type_return["flat"]["<7_days"]
    jump_quick = by_type_return["jump"]["<7_days"]
    flat_norm = by_type_return["flat"]["14-27_days"]   # baseline
    jump_norm = by_type_return["jump"]["14-27_days"]   # baseline

    comparison: dict = {}
    if flat_quick.runs >= 5:
        comparison["flat_quick_return_win_pct"] = round(flat_quick.win_pct, 1)
    if jump_quick.runs >= 5:
        comparison["jump_quick_return_win_pct"] = round(jump_quick.win_pct, 1)
    if flat_norm.runs >= 5:
        comparison["flat_normal_break_win_pct"] = round(flat_norm.win_pct, 1)
    if jump_norm.runs >= 5:
        comparison["jump_normal_break_win_pct"] = round(jump_norm.win_pct, 1)

    # Assessment
    assessment = "insufficient data"
    fq = comparison.get("flat_quick_return_win_pct")
    jq = comparison.get("jump_quick_return_win_pct")
    fn = comparison.get("flat_normal_break_win_pct")
    jn = comparison.get("jump_normal_break_win_pct")
    if fq is not None and jq is not None and fn is not None:
        if fq >= fn and jq < jn:
            assessment = f"CONFIRMED: flat quick return outperforms baseline ({fq}% vs {fn}%), jump quick return underperforms ({jq}% vs {jn}%)"
        elif fq >= fn and jq >= jn:
            assessment = f"PARTIALLY CONFIRMED: both flat and jump quick return OK, but flat gains more ({fq}% flat, {jq}% jump)"
        elif fq < fn:
            assessment = f"NOT CONFIRMED: flat quick return ({fq}%) below flat baseline ({fn}%)"
        else:
            assessment = f"AMBIGUOUS: flat={fq}% baseline={fn}%, jump={jq}% baseline={jn}%"

    return {
        "by_race_type_and_days_since_last_run": result,
        "quick_return_comparison": comparison,
        "assessment": assessment,
    }


# ---------------------------------------------------------------------------
# SUMMARY AND RECOMMENDATIONS
# ---------------------------------------------------------------------------

def generate_recommendations(
    draw_r: dict,
    age_r: dict,
    sex_r: dict,
    weight_r: dict,
    headgear_r: dict,
    wind_r: dict,
    commentary_r: dict,
    trainer_jockey_r: dict,
    quick_return_r: dict,
    total_runners_with_result: int,
) -> list[dict]:
    """
    Produce a ranked list of signal recommendations.
    Each item: {rank, signal, significance, recommendation, estimated_impact}.
    """
    recs: list[dict] = []

    # --- Draw ---
    top_courses = draw_r.get("top_5_biased_courses") or []
    if top_courses and draw_r.get("runners_analysed", 0) >= 50:
        max_bias = top_courses[0].get("bias_magnitude_pct", 0)
        if max_bias >= 5.0:
            course_names = ", ".join(c["course"] for c in top_courses[:3])
            direction = top_courses[0].get("direction", "")
            recs.append({
                "rank": None,
                "signal": "Draw Bias (Flat Racing)",
                "significance": "HIGH" if max_bias >= 8.0 else "MEDIUM",
                "evidence": f"Max course draw bias {max_bias:.1f}% at {top_courses[0]['course']} ({direction}). Top biased courses: {course_names}.",
                "recommendation": (
                    f"Add draw_score component to flat races. "
                    f"Example: +3pts for stalls 1-3 in sprints at {course_names} "
                    f"where low draw dominates. Check distance group tables for sprint vs mile split."
                ),
                "estimated_impact": "HIGH — draw at tight circuits (Chester, Catterick, Lingfield AW) can swing win probability by 10-15%.",
            })
    else:
        recs.append({
            "rank": None,
            "signal": "Draw Bias (Flat Racing)",
            "significance": "PENDING_DATA",
            "evidence": f"Only {draw_r.get('runners_analysed', 0)} runners with flat draw data. Need 200+ to establish bias.",
            "recommendation": "Run on PythonAnywhere after populating backtest_cache to get draw analysis.",
            "estimated_impact": "Expected HIGH once data available.",
        })

    # --- Quick return flat/jump split ---
    qr_comp = quick_return_r.get("quick_return_comparison") or {}
    qr_assess = quick_return_r.get("assessment", "insufficient data")
    if "CONFIRMED" in qr_assess:
        recs.append({
            "rank": None,
            "signal": "Quick Return (Flat vs Jump Split)",
            "significance": "HIGH",
            "evidence": qr_assess,
            "recommendation": (
                "Split the current _freshness_pts function by race type. "
                "For FLAT: +3pts for <7 days (currently +1pt only for 10-13 days). "
                "For JUMPS: remove or reduce quick-return bonus, possibly apply -1pt penalty."
            ),
            "estimated_impact": "MEDIUM-HIGH — pending fix already identified. Data confirms the split is real.",
        })
    else:
        fq = qr_comp.get("flat_quick_return_win_pct", "N/A")
        jq = qr_comp.get("jump_quick_return_win_pct", "N/A")
        recs.append({
            "rank": None,
            "signal": "Quick Return (Flat vs Jump Split)",
            "significance": "PENDING_DATA" if "insufficient" in qr_assess else "MEDIUM",
            "evidence": f"Flat quick return: {fq}%, Jump quick return: {jq}%. Assessment: {qr_assess}",
            "recommendation": "Collect more data. Already a known pending fix in the model.",
            "estimated_impact": "Expected MEDIUM — known model gap.",
        })

    # --- Trainer × Jockey combo ---
    n_hot_combos = trainer_jockey_r.get("total_trainer_jockey_combos_with_5plus_runs", 0)
    top_combos = trainer_jockey_r.get("top_10_hot_hands_combos") or []
    if top_combos:
        best_combo = top_combos[0]
        bc_edge = best_combo.get("combo_edge_over_solo_avg")
        bc_wp = best_combo.get("win_pct", 0)
        if bc_wp >= 25.0 and (bc_edge is None or bc_edge >= 3.0):
            significance = "HIGH"
        elif bc_wp >= 15.0:
            significance = "MEDIUM"
        else:
            significance = "LOW"
        recs.append({
            "rank": None,
            "signal": "Trainer × Jockey Hot Hands",
            "significance": significance,
            "evidence": (
                f"{n_hot_combos} combos with 5+ runs found. "
                f"Best: {best_combo.get('combo','?')} wins {bc_wp}% "
                f"({best_combo.get('wins','?')}/{best_combo.get('runs','?')} runs). "
                f"Combo edge over solo averages: {bc_edge}%."
            ),
            "recommendation": (
                "Add trainer_jockey_bonus score component (max +3pts). "
                "Trigger: trainer+jockey combo has 5+ runs AND win% >= 25%. "
                "This is entirely unmodelled currently — pure alpha."
            ),
            "estimated_impact": "MEDIUM — consistent partnerships win more predictably.",
        })
    else:
        recs.append({
            "rank": None,
            "signal": "Trainer × Jockey Hot Hands",
            "significance": "PENDING_DATA",
            "evidence": "No combos with 5+ runs in current data.",
            "recommendation": "Run on PythonAnywhere with populated backtest cache.",
            "estimated_impact": "Expected MEDIUM once data available.",
        })

    # --- Headgear ---
    hg_delta = headgear_r.get("first_time_vs_baseline_delta")
    hg_first_pct = headgear_r.get("first_time_win_pct")
    hg_runs = (headgear_r.get("by_headgear_status") or {}).get("first_time", {}).get("runs", 0)
    if hg_delta is not None and hg_runs >= 20:
        if hg_delta >= 3.0:
            sig = "MEDIUM"
            note = f"First-time headgear wins {hg_first_pct}% vs {headgear_r.get('baseline_no_headgear_win_pct')}% baseline (+{hg_delta}%). POSITIVE signal."
            rec = "Change current model note to a +2pt bonus for first-time headgear. Current code says 'not a positive signal' — data says otherwise."
        elif hg_delta >= 0:
            sig = "LOW"
            note = f"First-time headgear wins {hg_first_pct}% vs {headgear_r.get('baseline_no_headgear_win_pct')}% baseline (+{hg_delta}%). Neutral to mildly positive."
            rec = "Current model treatment (note only, no points) is approximately correct. Monitor second-time headgear separately."
        else:
            sig = "MEDIUM"
            note = f"First-time headgear wins {hg_first_pct}% vs {headgear_r.get('baseline_no_headgear_win_pct')}% baseline ({hg_delta}%). NEGATIVE signal — current model code correct."
            rec = "Current note 'not a positive signal per data' is confirmed. Consider adding -2pt penalty for first-time headgear."
        recs.append({
            "rank": None, "signal": "Headgear First-Time",
            "significance": sig, "evidence": note, "recommendation": rec,
            "estimated_impact": "LOW-MEDIUM — headgear is an infrequent signal but high-profile.",
        })
    else:
        recs.append({
            "rank": None, "signal": "Headgear First-Time",
            "significance": "PENDING_DATA",
            "evidence": f"Only {hg_runs} first-time headgear runners with results.",
            "recommendation": "Needs 20+ first-time headgear cases to be statistically meaningful.",
            "estimated_impact": "Expected LOW-MEDIUM.",
        })

    # --- Wind surgery calibration ---
    ws_note = wind_r.get("calibration_note", "insufficient data")
    ws_first = wind_r.get("first_run_win_pct")
    ws_base = wind_r.get("baseline_win_pct")
    ws_runs = wind_r.get("first_run_after_surgery", {}).get("runs", 0)
    if ws_first is not None and ws_base is not None and ws_runs >= 10:
        delta_ws = round(ws_first - ws_base, 1)
        if abs(delta_ws) >= 3.0:
            sig = "MEDIUM"
        else:
            sig = "LOW"
        recs.append({
            "rank": None, "signal": "Wind Surgery Calibration",
            "significance": sig,
            "evidence": f"Wind surgery first run: {ws_first}%, baseline: {ws_base}%, delta: {delta_ws}%. {ws_note}",
            "recommendation": (
                f"Current model: +3pts. "
                f"{'Increase to +5pts' if delta_ws >= 5.0 else 'Keep at +3pts' if delta_ws >= 2.0 else 'Reduce to +1pt or remove'}."
            ),
            "estimated_impact": "LOW — wind surgery is a rare signal but already modelled.",
        })
    else:
        recs.append({
            "rank": None, "signal": "Wind Surgery Calibration",
            "significance": "PENDING_DATA",
            "evidence": f"Only {ws_runs} wind surgery first run cases. Need 10+.",
            "recommendation": "Current +3pt bonus is a sensible default. Revisit with more data.",
            "estimated_impact": "LOW — rare signal.",
        })

    # --- Commentary NLP ---
    commentary_by_sent = commentary_r.get("by_sentiment") or {}
    coverage = commentary_r.get("commentary_coverage_pct", 0)
    sp_stats = commentary_by_sent.get("strong_positive") or {}
    sn_stats = commentary_by_sent.get("strong_negative") or {}
    sp_pct = sp_stats.get("win_pct", 0)
    sn_pct = sn_stats.get("win_pct", 0)
    baseline_sent = commentary_r.get("baseline_neutral_win_pct")
    high_alpha = commentary_r.get("high_alpha_keywords") or []

    if coverage >= 20 and baseline_sent is not None:
        delta_sp = round(sp_pct - baseline_sent, 1) if sp_stats.get("runs", 0) >= 10 else None
        delta_sn = round(sn_pct - baseline_sent, 1) if sn_stats.get("runs", 0) >= 10 else None
        if delta_sp is not None and delta_sp >= 5.0:
            sig = "MEDIUM"
            note = f"Strong positive commentary: {sp_pct}% win rate (+{delta_sp}% over neutral). Alpha present."
        elif delta_sp is not None:
            sig = "LOW"
            note = f"Positive commentary: {sp_pct}% win rate ({delta_sp:+}% vs neutral). Marginal."
        else:
            sig = "PENDING_DATA"
            note = f"Commentary coverage {coverage}% but few strong-positive cases."
        top_kw = [k["keyword"] for k in high_alpha[:5]] if high_alpha else []
        recs.append({
            "rank": None, "signal": "Commentary / Spotlight NLP",
            "significance": sig,
            "evidence": f"Coverage: {coverage}%. {note}. Top alpha keywords: {top_kw}.",
            "recommendation": (
                "Add commentary_score component (max +3pts). "
                "Trigger: spotlight/quotes contains strong_positive keywords. "
                "Stable-tour quotes ('should win', 'very well') are highest alpha."
            ),
            "estimated_impact": "LOW-MEDIUM — commentary is already partially modelled (+2pts for 'stable commentary present') but keyword sentiment is not.",
        })
    else:
        recs.append({
            "rank": None, "signal": "Commentary / Spotlight NLP",
            "significance": "PENDING_DATA",
            "evidence": f"Commentary coverage: {coverage}% (need 20%+ to be useful).",
            "recommendation": "Commentary fields may not be populated in backtest cache. Run with live data.",
            "estimated_impact": "Expected LOW-MEDIUM.",
        })

    # --- Age ---
    age_by = age_r.get("by_age") or {}
    if len(age_by) >= 3:
        # Find highest win % age group vs average
        age_win_rates = {k: v.get("win_pct", 0) for k, v in age_by.items() if v.get("runs", 0) >= 20}
        if age_win_rates:
            best_age = max(age_win_rates, key=lambda x: age_win_rates[x])
            worst_age = min(age_win_rates, key=lambda x: age_win_rates[x])
            spread = age_win_rates[best_age] - age_win_rates[worst_age]
            sig = "MEDIUM" if spread >= 5.0 else "LOW"
            recs.append({
                "rank": None, "signal": "Age Patterns",
                "significance": sig,
                "evidence": f"Best: {best_age} ({age_win_rates[best_age]:.1f}% win). Worst: {worst_age} ({age_win_rates[worst_age]:.1f}% win). Spread: {spread:.1f}%.",
                "recommendation": (
                    f"Consider age penalty for {worst_age} horses in competitive races. "
                    "2yo and 3yo debutants have higher variance — flagging in Shadow list."
                ),
                "estimated_impact": "LOW — age interacts with class level, complex to model cleanly.",
            })

    # --- Sex patterns ---
    sex_by = sex_r.get("by_sex") or {}
    if len(sex_by) >= 2:
        sex_win_rates = {k: v.get("win_pct", 0) for k, v in sex_by.items() if v.get("runs", 0) >= 20}
        if len(sex_win_rates) >= 2:
            best_sex = max(sex_win_rates, key=lambda x: sex_win_rates[x])
            worst_sex = min(sex_win_rates, key=lambda x: sex_win_rates[x])
            sex_spread = sex_win_rates[best_sex] - sex_win_rates[worst_sex]
            sex_var = sex_r.get("sex_position_variance") or {}
            gelding_var = sex_var.get("Gelding")
            filly_var = sex_var.get("Filly")
            var_note = ""
            if gelding_var and filly_var:
                var_note = f" Gelding position std dev: {gelding_var}, Filly: {filly_var}."
            recs.append({
                "rank": None, "signal": "Sex / Gender Patterns",
                "significance": "MEDIUM" if sex_spread >= 4.0 else "LOW",
                "evidence": f"Best: {best_sex} ({sex_win_rates[best_sex]:.1f}% win). Worst: {worst_sex} ({sex_win_rates[worst_sex]:.1f}% win). Spread: {sex_spread:.1f}%.{var_note}",
                "recommendation": (
                    "Geldings are more consistent (lower variance) — "
                    "consider +1pt for geldings in handicaps. Fillies/mares have higher variance — "
                    "consider flagging with uncertainty note."
                ),
                "estimated_impact": "LOW — marginal signal, not worth major model change alone.",
            })

    # --- Weight ---
    wt_sweet = weight_r.get("sweet_spot_bracket")
    wt_pct = weight_r.get("sweet_spot_win_pct")
    wt_by = weight_r.get("by_weight_bracket") or {}
    if wt_sweet and wt_pct and len(wt_by) >= 3:
        # Compare topweight to sweet spot
        heavy_stats = wt_by.get("9-7 to 9-13") or wt_by.get("10-0+ (topweight)") or {}
        heavy_pct = heavy_stats.get("win_pct", 0)
        penalty_evidence = f"Sweet spot: {wt_sweet} ({wt_pct}% win). Heavy weight (9-7+): {heavy_pct}%."
        spread_wt = wt_pct - heavy_pct
        recs.append({
            "rank": None, "signal": "Weight Carried",
            "significance": "MEDIUM" if spread_wt >= 4.0 else "LOW",
            "evidence": penalty_evidence,
            "recommendation": (
                "Weight is already implicitly captured via OR (official rating). "
                "However, top weight in handicaps (9-7+) deserves explicit -2pt penalty "
                "if win rate is materially below average."
            ),
            "estimated_impact": "LOW — weight correlates with class/OR which is already scored.",
        })

    # --- Rank by significance ---
    significance_order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2, "PENDING_DATA": 3}
    recs.sort(key=lambda r: significance_order.get(r.get("significance", "PENDING_DATA"), 3))
    for i, r in enumerate(recs, 1):
        r["rank"] = i

    return recs


# ---------------------------------------------------------------------------
# Report formatting
# ---------------------------------------------------------------------------

def _format_report(
    date_str: str,
    total_races: int,
    total_runners: int,
    total_runners_with_result: int,
    draw_r: dict,
    age_r: dict,
    sex_r: dict,
    weight_r: dict,
    headgear_r: dict,
    wind_r: dict,
    commentary_r: dict,
    trainer_jockey_r: dict,
    quick_return_r: dict,
    recommendations: list[dict],
) -> str:
    SEP = "=" * 72
    sep = "-" * 72
    lines = [
        SEP,
        "  RACING EDGE — HIDDEN SIGNALS MINING REPORT",
        f"  Generated: {date_str}",
        f"  Data: {total_races} races | {total_runners} runners | {total_runners_with_result} with result data",
        SEP,
    ]

    def _section(title: str):
        lines.append("")
        lines.append(f"{'█' * 2} {title}")
        lines.append(sep)

    # ---- Draw ----
    _section("SIGNAL 1: DRAW BIAS (FLAT RACING)")
    if draw_r.get("runners_analysed", 0) == 0:
        lines.append("  No flat draw data in cache. Run on PythonAnywhere to populate.")
    else:
        lines.append(f"  Runners analysed: {draw_r.get('runners_analysed')} across {draw_r.get('races_with_flat_draw_data')} races")
        for dist, thirds in (draw_r.get("by_distance_group") or {}).items():
            low = thirds.get("low") or {}
            mid = thirds.get("mid") or {}
            high = thirds.get("high") or {}
            lines.append(
                f"  {dist:<22} "
                f"Low draw: {low.get('win_pct', 0):>5.1f}% ({low.get('runs', 0):>4} runs)  "
                f"Mid: {mid.get('win_pct', 0):>5.1f}% ({mid.get('runs', 0):>4})  "
                f"High: {high.get('win_pct', 0):>5.1f}% ({high.get('runs', 0):>4})"
            )
        lines.append("")
        lines.append("  Top Biased Courses:")
        if draw_r.get("top_5_biased_courses"):
            for c in draw_r["top_5_biased_courses"]:
                lines.append(
                    f"    {c['course']:<20} {c['direction']:<22} bias={c['bias_magnitude_pct']:>4.1f}%  "
                    f"low={c.get('low_win_pct', 0):.1f}% mid={c.get('mid_win_pct', 0):.1f}% high={c.get('high_win_pct', 0):.1f}%"
                )
        else:
            lines.append("    Insufficient data (need 20+ runs per course)")

    # ---- Age ----
    _section("SIGNAL 2: AGE PATTERNS")
    age_by = age_r.get("by_age") or {}
    if age_by:
        lines.append(f"  {'Age':<10} {'Runs':>6} {'Wins':>5} {'Win%':>6} {'Place%':>7} {'PosStdDev':>10}")
        for bucket in ["2yo", "3yo", "4yo", "5yo", "6yo", "7yo+"]:
            if bucket in age_by:
                d = age_by[bucket]
                std = d.get("position_std_dev")
                std_s = f"{std:.2f}" if std else "  N/A"
                lines.append(
                    f"  {bucket:<10} {d.get('runs', 0):>6} {d.get('wins', 0):>5} "
                    f"{d.get('win_pct', 0):>5.1f}% {d.get('place_pct', 0):>6.1f}% {std_s:>10}"
                )
    else:
        lines.append("  No age data available.")

    # ---- Sex ----
    _section("SIGNAL 3: SEX / GENDER PATTERNS")
    sex_by = sex_r.get("by_sex") or {}
    if sex_by:
        lines.append(f"  {'Sex':<20} {'Runs':>6} {'Wins':>5} {'Win%':>6} {'Place%':>7} {'PosStdDev':>10}")
        for bkt, d in sorted(sex_by.items(), key=lambda x: -x[1].get("win_pct", 0)):
            if d.get("runs", 0) >= 5:
                std = d.get("position_std_dev")
                std_s = f"{std:.2f}" if std else "  N/A"
                lines.append(
                    f"  {bkt:<20} {d.get('runs', 0):>6} {d.get('wins', 0):>5} "
                    f"{d.get('win_pct', 0):>5.1f}% {d.get('place_pct', 0):>6.1f}% {std_s:>10}"
                )
    else:
        lines.append("  No sex data available.")

    # ---- Weight ----
    _section("SIGNAL 4: WEIGHT CARRIED")
    wt_by = weight_r.get("by_weight_bracket") or {}
    if wt_by:
        sweet = weight_r.get("sweet_spot_bracket")
        lines.append(f"  {'Weight Bracket':<25} {'Runs':>6} {'Wins':>5} {'Win%':>6}")
        ordered_buckets = [
            "<8-7 (featherweight)",
            "8-7 to 8-13",
            "9-0 to 9-6",
            "9-7 to 9-13",
            "10-0+ (topweight)",
            "Unknown",
        ]
        for bkt in ordered_buckets:
            d = wt_by.get(bkt)
            if not d or d.get("runs", 0) < 5:
                continue
            marker = " ***SWEET SPOT***" if bkt == sweet else ""
            lines.append(
                f"  {bkt:<25} {d.get('runs', 0):>6} {d.get('wins', 0):>5} "
                f"{d.get('win_pct', 0):>5.1f}%{marker}"
            )
        for bkt, d in wt_by.items():
            if bkt not in ordered_buckets and d.get("runs", 0) >= 5:
                marker = " ***SWEET SPOT***" if bkt == sweet else ""
                lines.append(
                    f"  {bkt:<25} {d.get('runs', 0):>6} {d.get('wins', 0):>5} "
                    f"{d.get('win_pct', 0):>5.1f}%{marker}"
                )
    else:
        lines.append("  No weight data available.")

    # ---- Headgear ----
    _section("SIGNAL 5: HEADGEAR FIRST-TIME ANALYSIS")
    hg_by = headgear_r.get("by_headgear_status") or {}
    baseline_hg = headgear_r.get("baseline_no_headgear_win_pct")
    delta_hg = headgear_r.get("first_time_vs_baseline_delta")
    if hg_by:
        lines.append(f"  {'Status':<20} {'Runs':>6} {'Wins':>5} {'Win%':>6}")
        for status in ["no_headgear", "first_time", "second_time", "established"]:
            d = hg_by.get(status)
            if d and d.get("runs", 0) >= 3:
                lines.append(
                    f"  {status:<20} {d.get('runs', 0):>6} {d.get('wins', 0):>5} {d.get('win_pct', 0):>5.1f}%"
                )
        if baseline_hg is not None:
            lines.append(f"  Baseline (no headgear): {baseline_hg}%")
        if delta_hg is not None:
            delta_arrow = "^" if delta_hg > 0 else "v"
            lines.append(f"  First-time headgear vs baseline: {delta_hg:+.1f}% ({delta_arrow})")

        # By headgear type
        hg_types = headgear_r.get("first_time_by_headgear_type") or {}
        if hg_types:
            lines.append("  By headgear type (first time only):")
            for hg_type, d in sorted(hg_types.items(), key=lambda x: -x[1].get("win_pct", 0)):
                if d.get("runs", 0) >= 3:
                    lines.append(
                        f"    {hg_type:<20} {d.get('runs', 0):>4} runs  {d.get('win_pct', 0):>5.1f}% win"
                    )
    else:
        lines.append("  No headgear data available.")

    # ---- Wind surgery ----
    _section("SIGNAL 6: WIND SURGERY (current model: +3pts)")
    wf_first = wind_r.get("first_run_win_pct")
    wf_base = wind_r.get("baseline_win_pct")
    wf_note = wind_r.get("calibration_note", "insufficient data")
    wf_runs = wind_r.get("first_run_after_surgery", {}).get("runs", 0)
    lines.append(f"  First run after wind surgery: {wf_runs} cases")
    if wf_first is not None:
        lines.append(f"  Win rate:  {wf_first}%  (first run after surgery)")
    if wf_base is not None:
        lines.append(f"  Baseline:  {wf_base}%  (no surgery horses)")
    lines.append(f"  Calibration: {wf_note}")

    # ---- Commentary ----
    _section("SIGNAL 7: SPOTLIGHT / COMMENTARY NLP")
    coverage = commentary_r.get("commentary_coverage_pct", 0)
    lines.append(f"  Commentary coverage: {coverage}%")
    sent_by = commentary_r.get("by_sentiment") or {}
    baseline_sent = commentary_r.get("baseline_neutral_win_pct")
    if baseline_sent:
        lines.append(f"  Neutral commentary baseline: {baseline_sent}%")
    lines.append(f"  {'Sentiment':<20} {'Runs':>6} {'Wins':>5} {'Win%':>6}")
    for bucket in ["strong_positive", "mild_positive", "neutral", "mild_negative", "strong_negative", "no_commentary"]:
        d = sent_by.get(bucket)
        if d and d.get("runs", 0) >= 3:
            lines.append(
                f"  {bucket:<20} {d.get('runs', 0):>6} {d.get('wins', 0):>5} {d.get('win_pct', 0):>5.1f}%"
            )
    high_alpha = commentary_r.get("high_alpha_keywords") or []
    if high_alpha:
        lines.append("  High-alpha keywords (10+ occurrences):")
        for kw in high_alpha[:10]:
            lines.append(
                f"    {kw['keyword']:<30} {kw['runs']:>4} runs  win={kw['win_pct']:.1f}%  vs_baseline={kw['vs_baseline']:+.1f}%"
            )

    # ---- Trainer × Jockey ----
    _section("SIGNAL 8: TRAINER x JOCKEY HOT HANDS")
    n_combos = trainer_jockey_r.get("total_trainer_jockey_combos_with_5plus_runs", 0)
    lines.append(f"  Combos with 5+ runs: {n_combos}")
    top_combos = trainer_jockey_r.get("top_10_hot_hands_combos") or []
    if top_combos:
        lines.append(f"  {'Combo':<45} {'Runs':>5} {'Win%':>6} {'Edge':>6}")
        for c in top_combos[:10]:
            edge_s = f"{c.get('combo_edge_over_solo_avg', 0):+.1f}%" if c.get("combo_edge_over_solo_avg") is not None else "  N/A"
            lines.append(
                f"  {c.get('combo', '?'):<45} {c.get('runs', 0):>5} {c.get('win_pct', 0):>5.1f}% {edge_s:>6}"
            )
    lines.append(f"  Note: {trainer_jockey_r.get('model_gap_note', '')}")

    # ---- Quick return ----
    _section("SIGNAL 9: QUICK RETURN — FLAT vs JUMPS (PENDING FIX)")
    qr_comp = quick_return_r.get("quick_return_comparison") or {}
    qr_assess = quick_return_r.get("assessment", "insufficient data")
    lines.append(f"  Assessment: {qr_assess}")
    if qr_comp:
        for key, val in qr_comp.items():
            lines.append(f"    {key}: {val}%")
    qr_by_type = quick_return_r.get("by_race_type_and_days_since_last_run") or {}
    for type_tag in ("flat", "jump"):
        type_data = qr_by_type.get(type_tag) or {}
        if type_data:
            lines.append(f"  {type_tag.upper()} return profile:")
            for bkt in ["<7_days", "7-13_days", "14-27_days", "28-44_days", "45-69_days", "70+_days"]:
                d = type_data.get(bkt)
                if d and d.get("runs", 0) >= 5:
                    lines.append(
                        f"    {bkt:<15} {d.get('runs', 0):>5} runs  win={d.get('win_pct', 0):>5.1f}%  place={d.get('place_pct', 0):>5.1f}%"
                    )

    # ---- Top 5 recommendations ----
    _section("TOP RECOMMENDATIONS (RANKED BY ESTIMATED IMPACT)")
    if not recommendations:
        lines.append("  No recommendations (no data — run on PythonAnywhere to populate).")
    else:
        for rec in recommendations[:5]:
            lines.append(f"  #{rec['rank']}  [{rec['significance']}]  {rec['signal']}")
            lines.append(f"     Evidence:       {rec.get('evidence', '')}")
            lines.append(f"     Recommendation: {rec.get('recommendation', '')}")
            lines.append(f"     Est. Impact:    {rec.get('estimated_impact', '')}")
            lines.append("")

    lines.append(SEP)
    lines.append("  NOTE: This report is based on cached backtest data.")
    lines.append("  If cache is empty, all 'PENDING_DATA' signals need PythonAnywhere run.")
    lines.append("  Recommended: python historical_backtest.py --months 6  (populate cache)")
    lines.append("  Then:        python hidden_signals_miner.py  (re-run analysis)")
    lines.append(SEP)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Mine hidden predictive signals from cached backtest data."
    )
    parser.add_argument(
        "--cache-dir",
        type=str,
        default=None,
        help="Override backtest cache directory (default: data/backtest_cache/)",
    )
    args = parser.parse_args()

    date_str = date.today().isoformat()
    print(f"hidden_signals_miner.py — {date_str}")

    cache_base = _cache_dir(args.cache_dir)
    print(f"Cache directory: {cache_base}")

    # --- Load data ---
    print("Loading racecards from cache...")
    all_races = load_all_racecards(cache_base)
    print(f"  Loaded {len(all_races)} races from cache.")

    print("Loading results lookup from cache...")
    result_lookup = load_results_lookup(cache_base)
    print(f"  Loaded {len(result_lookup)} horse results.")

    if not all_races:
        print(
            "\nWARNING: No cached racecards found at:\n"
            f"  {cache_base}/racecards/\n\n"
            "To populate: run  python historical_backtest.py --months 6\n"
            "on PythonAnywhere where API credentials are available.\n\n"
            "Proceeding with empty analysis — output will show structure only."
        )

    total_races = len(all_races)
    total_runners = sum(len(r.get("runners") or []) for r in all_races)

    # Count runners with result data
    total_runners_with_result = 0
    for race in all_races:
        for runner in (race.get("runners") or []):
            pos_int, _ = _get_position(runner, result_lookup)
            if pos_int != 99:
                total_runners_with_result += 1

    print(f"  Total runners: {total_runners}, with result data: {total_runners_with_result}")

    # --- Run analyses ---
    print("Analysing draw bias...")
    draw_r = analyse_draw(all_races, result_lookup)

    print("Analysing age patterns...")
    age_r = analyse_age(all_races, result_lookup)

    print("Analysing sex/gender patterns...")
    sex_r = analyse_sex(all_races, result_lookup)

    print("Analysing weight carried...")
    weight_r = analyse_weight(all_races, result_lookup)

    print("Analysing headgear signals...")
    headgear_r = analyse_headgear(all_races, result_lookup)

    print("Analysing wind surgery signal...")
    wind_r = analyse_wind_surgery(all_races, result_lookup)

    print("Analysing commentary / spotlight NLP...")
    commentary_r = analyse_commentary(all_races, result_lookup)

    print("Analysing trainer x jockey combinations...")
    trainer_jockey_r = analyse_trainer_jockey(all_races, result_lookup)

    print("Analysing quick return (flat vs jump split)...")
    quick_return_r = analyse_quick_return(all_races, result_lookup)

    # --- Generate recommendations ---
    print("Generating recommendations...")
    recommendations = generate_recommendations(
        draw_r, age_r, sex_r, weight_r, headgear_r, wind_r,
        commentary_r, trainer_jockey_r, quick_return_r,
        total_runners_with_result,
    )

    # --- Format report ---
    report_text = _format_report(
        date_str=date_str,
        total_races=total_races,
        total_runners=total_runners,
        total_runners_with_result=total_runners_with_result,
        draw_r=draw_r,
        age_r=age_r,
        sex_r=sex_r,
        weight_r=weight_r,
        headgear_r=headgear_r,
        wind_r=wind_r,
        commentary_r=commentary_r,
        trainer_jockey_r=trainer_jockey_r,
        quick_return_r=quick_return_r,
        recommendations=recommendations,
    )

    # --- Write outputs ---
    report_file = _report_path(f"hidden_signals_{date_str}.txt")
    try:
        with open(report_file, "w", encoding="utf-8") as fh:
            fh.write(report_text)
        print(f"\nReport written: {report_file}")
    except OSError as exc:
        print(f"ERROR: Failed to write report — {exc}", file=sys.stderr)
        return 1

    json_payload = {
        "generated_at": date_str,
        "data_summary": {
            "total_races": total_races,
            "total_runners": total_runners,
            "runners_with_result": total_runners_with_result,
        },
        "signals": {
            "1_draw_bias": draw_r,
            "2_age_patterns": age_r,
            "3_sex_patterns": sex_r,
            "4_weight_carried": weight_r,
            "5_headgear_first_time": headgear_r,
            "6_wind_surgery": wind_r,
            "7_commentary_nlp": commentary_r,
            "8_trainer_jockey_combos": trainer_jockey_r,
            "9_quick_return_split": quick_return_r,
        },
        "recommendations": recommendations,
    }

    json_file = _data_path(f"hidden_signals_{date_str}.json")
    try:
        with open(json_file, "w", encoding="utf-8") as fh:
            json.dump(json_payload, fh, indent=2, ensure_ascii=False)
        print(f"JSON written:   {json_file}")
    except (OSError, TypeError, ValueError) as exc:
        print(f"ERROR: Failed to write JSON — {exc}", file=sys.stderr)
        return 1

    # --- Print top 5 signals ---
    print("\n" + "=" * 72)
    print("  TOP 5 HIDDEN SIGNALS (RANKED BY ESTIMATED IMPACT)")
    print("=" * 72)
    for rec in recommendations[:5]:
        print(f"\n  #{rec['rank']}  [{rec['significance']}]  {rec['signal']}")
        print(f"     {rec.get('evidence', '')}")
        print(f"     -> {rec.get('recommendation', '')}")
        print(f"     Impact: {rec.get('estimated_impact', '')}")

    if total_runners_with_result == 0:
        print(
            "\n  NOTE: Cache is empty — all signals show PENDING_DATA.\n"
            "  Populate with: python historical_backtest.py --months 6\n"
            "  Then re-run:   python hidden_signals_miner.py"
        )

    print("\n" + "=" * 72)
    return 0


if __name__ == "__main__":
    sys.exit(main())
