"""
intelligence_rules.py — Machine-readable intelligence rules for the NAP model.
Auto-generated by intelligence_brief_builder.py on 2026-06-08.

Import these constants into the new model to implement proven edges.
"""

from __future__ import annotations

# ─────────────────────────────────────────────────────────────────────────────
# CONFIRMED EDGES  (from score_attribution analysis, n=60)
# ─────────────────────────────────────────────────────────────────────────────

CONFIRMED_EDGES: list[dict] = [
    {
        "name": "Grade A dominance over Grade B+",
        "magnitude": "Grade A: 30.0% WR / ROI +94.1% vs Grade B+: 8.3% WR / ROI -61.9%",
        "implementation": "Only select NAPs from Grade A (score >= 70). Grade B+ is a loss zone.",
        "confidence": "HIGH",
        "sample_size": 30,
        "roi": 94.1
    },
    {
        "name": "Score >= 73 maximum ROI threshold",
        "magnitude": "32.1% WR, ROI +108.0%, n=28",
        "implementation": "Set NAP_MIN_SCORE = 73 for ROI-optimal staking",
        "confidence": "HIGH",
        "sample_size": 28,
        "roi": 108.0
    },
    {
        "name": "Grade A hurdle selections outperform Grade A chases",
        "magnitude": "A\u00d7Hurdle: 50.0% WR / ROI +235.7% vs A\u00d7Chase: 18.8% WR / ROI +9.6%",
        "implementation": "De-prioritise chases. Focus NAP hunt on hurdle races.",
        "confidence": "MEDIUM",
        "sample_size": 10,
        "roi": 235.7
    },
    {
        "name": "Grade A in Class 5 & 3 massively outperforms Class 1-2 and Class 4",
        "magnitude": "A\u00d7Class5: 36.4% / ROI +213.1%, A\u00d7Class3: 50.0% / ROI +195.5%, A\u00d7Class1-2: 14.3% / ROI -49.7%, A\u00d7Class4: 16.7% / ROI -57.5%",
        "implementation": "Apply Class 1-2 and Class 4 PENALTY or veto for NAP selection.",
        "confidence": "MEDIUM",
        "sample_size": 17,
        "roi": 213.1
    },
    {
        "name": "Trainer Intent is the strongest sub-score predictor",
        "magnitude": "Pearson r=0.2693, avg winner 7.29 vs loser 5.10 (+2.19 diff)",
        "implementation": "Increase Trainer Intent weight. Consider doubling its ceiling from 15 \u2192 20pts.",
        "confidence": "MEDIUM",
        "sample_size": 60,
        "pearson_r": 0.2693
    },
    {
        "name": "Model over-scores losers \u2014 100% of missed winners had LOWER score than our pick",
        "magnitude": "9/9 missed-winner days: winner scored LOWER than our pick (100%)",
        "implementation": "High score alone is insufficient. Need discriminatory secondary filters.",
        "confidence": "HIGH",
        "sample_size": 9
    },
    {
        "name": "Golden Zone: Grade A, Hurdle, Class 5",
        "magnitude": "40.0% WR, ROI +261.6%, n=5",
        "implementation": "Apply +5pt bonus when Grade A + Hurdle + Class 5 all present",
        "confidence": "LOW",
        "sample_size": 5,
        "roi": 261.6
    }
]


# ─────────────────────────────────────────────────────────────────────────────
# VETO CONDITIONS  (hard NO-BET triggers)
# ─────────────────────────────────────────────────────────────────────────────

VETO_CONDITIONS: list[dict] = [
    {"condition": "dangerous_drift in warnings", "label": "Market dangerous drift"},
    {"condition": "60 <= score < 70", "label": "Grade B+ zone (8.3% WR)"},
    {"condition": "score > 82", "label": "Score ceiling trap (0% WR at 83-85)"},
    {"condition": "class in (1, 2, 4)", "label": "Class 1-2 or 4 (negative ROI)"},
    {"condition": "race_type == chase", "label": "Chase excluded"},
    {"condition": "flat AND going in excluded_list", "label": "Flat bad going"},
]


# ─────────────────────────────────────────────────────────────────────────────
# PREDICTION RECIPE  (must-have conditions for an ideal NAP)
# ─────────────────────────────────────────────────────────────────────────────

PREDICTION_RECIPE: dict = {
    "description": "Ideal NAP: score 73-82, Grade A hurdle, Class 3 or 5, hot trainer",
    "optimal_threshold": 73,
    "score_ceiling_cap": 82,
    "optimal_roi_pct": 108.0,
    "optimal_win_rate_pct": 32.1,
    "must_have": [
    {"condition": "score >= 70.0", "label": "Grade A", "basis": "30.0% WR vs 8.3% B+"},
    {"condition": "trainer_score >= 5", "label": "Trainer Intent", "basis": "r=+0.27"},
    {"condition": "race_type == hurdle", "label": "Hurdle only", "basis": "50% WR vs 18.8% chase"},
    {"condition": "class in (3, 5)", "label": "Class 3 or 5", "basis": "ROI +195-213%"},
    {"condition": "73 <= score <= 82", "label": "Score sweet spot", "basis": "83-85 = 0% WR"},
    ],
    "veto_conditions": VETO_CONDITIONS,
}


# ─────────────────────────────────────────────────────────────────────────────
# MODEL EVOLUTION ROADMAP
# ─────────────────────────────────────────────────────────────────────────────

MODEL_ROADMAP: list[dict] = [
    {
        "priority": "P1",
        "impact": "HIGH IMPACT, EASY",
        "change": "Raise NAP_MIN_SCORE from 63 \u2192 73",
        "expected_improvement": "+54% ROI improvement (from +54% to +108%)",
        "effort": "1-line config change",
        "basis": "Threshold sweep analysis: score>=73 = +108% ROI vs score>=63 = +54% ROI"
    },
    {
        "priority": "P1",
        "impact": "HIGH IMPACT, EASY",
        "change": "Add Grade B+ hard veto to NAP selection",
        "expected_improvement": "Eliminates 12 losing bets (8.3% WR, -61.9% ROI bucket)",
        "effort": "Add 1 condition to main() filter",
        "basis": "Grade B+ is active money destruction"
    },
    {
        "priority": "P1",
        "impact": "HIGH IMPACT, MEDIUM",
        "change": "Invert class scoring in context score",
        "expected_improvement": "+30-50% estimated ROI from class realignment",
        "effort": "Rewrite compute_context_score class ladder (10 lines)",
        "basis": "Class 5 = +213% ROI, Class 1-2 = -50% ROI; current model is inverted"
    },
    {
        "priority": "P2",
        "impact": "HIGH IMPACT, MEDIUM",
        "change": "Add score ceiling cap \u2014 flag/penalise scores > 82",
        "expected_improvement": "Rescues ~6 bets per period (0% WR zone)",
        "effort": "Post-scoring adjustment in score_runner()",
        "basis": "Band 83-85 = 0% WR (n=6), near-miss analysis confirms pattern"
    },
    {
        "priority": "P2",
        "impact": "HIGH IMPACT, HARDER",
        "change": "Increase Trainer Intent ceiling 15 \u2192 20pts",
        "expected_improvement": "+5-10% estimated WR improvement",
        "effort": "Recalibrate trainer tiers and ceiling in compute_trainer_score()",
        "basis": "Strongest sub-score predictor (r=+0.27), currently chronically unclaimed"
    },
    {
        "priority": "P2",
        "impact": "MEDIUM IMPACT, MEDIUM",
        "change": "Remove Market Overlay steamer bonus; keep only drift veto",
        "expected_improvement": "Neutralise negative r=-0.12 drag",
        "effort": "Edit compute_market_score() \u2014 remove positive score path",
        "basis": "Market overlay has negative correlation \u2014 rewarding steamers hurts performance"
    },
    {
        "priority": "P3",
        "impact": "MEDIUM IMPACT, HARDER",
        "change": "Populate backtest cache and re-run hidden signals miner",
        "expected_improvement": "Unlocks draw bias, trainer\u00d7jockey, headgear signals",
        "effort": "Run historical_backtest.py on PythonAnywhere (data pipeline)",
        "basis": "All hidden signals pending data; estimated HIGH impact for draw bias"
    },
    {
        "priority": "P3",
        "impact": "MEDIUM IMPACT, MEDIUM",
        "change": "Apply Golden Zone bonus: Grade A + Hurdle + Class 5 = +5pts",
        "expected_improvement": "Boost selection of highest-ROI combo (+261.6%)",
        "effort": "Add combo bonus in score_runner() post-computation",
        "basis": "Hurdle \u00d7 Class 5 Grade A = 40% WR, +261.6% ROI (needs more data)"
    },
    {
        "priority": "P3",
        "impact": "LOW-MEDIUM IMPACT, EASY",
        "change": "Implement jockey \u00d7 trainer combo bonus (+2 to +5pts)",
        "expected_improvement": "Expected MEDIUM impact per hidden signals analysis",
        "effort": "Add jockey_trainer_combo lookup to compute_trainer_score()",
        "basis": "Current model ignores jockey entirely; model gap note in hidden signals"
    },
    {
        "priority": "P4",
        "impact": "LOW IMPACT, LONG-TERM",
        "change": "Recalibrate all sub-score ranges to utilise full 0-100 space",
        "expected_improvement": "Improve score discrimination; reduce compression artifact",
        "effort": "Full scoring audit and range expansion",
        "basis": "All 5 components chronically unclaimed; mean utilisation ~35-48% of ceiling"
    }
]


# ─────────────────────────────────────────────────────────────────────────────
# SCORE THRESHOLDS  (data-backed replacements for current defaults)
# ─────────────────────────────────────────────────────────────────────────────

# Current value: 63.0  →  Data-backed optimum: 73.0
OPTIMAL_NAP_MIN_SCORE: float = 73.0

# Current value: 70.0  →  Confirmed correct (Grade A threshold)
OPTIMAL_GRADE_A_THRESHOLD: float = 70.0

# New: Score ceiling beyond which the model is unreliable (inverts to 0% WR)
SCORE_CEILING_TRAP: float = 82.0

# Grade B+ zone — never NAP (8.3% WR, ROI -61.9%)
GRADE_BPLUS_NAP_VETO_LOWER: float = 60.0
GRADE_BPLUS_NAP_VETO_UPPER: float = 70.0


# ─────────────────────────────────────────────────────────────────────────────
# CLASS SCORING INVERSION  (current model rewards wrong classes)
# ─────────────────────────────────────────────────────────────────────────────

# Current model: Class 1-2 = +5pts, Class 5 = -2pts  (WRONG — hurts ROI)
# Data-backed:   Class 3   = +5pts ROI +195%, Class 5 = +3pts ROI +213%
#                Class 1-2 = -2pts ROI -50%,  Class 4 = -3pts ROI -57%
CLASS_SCORING_DATA_BACKED: dict[int, float] = {
    1: -2.0,   # Class 1 — prestige but model edge vanishes; ROI -49.7%
    2: -2.0,   # Class 2 — same as Class 1
    3: +5.0,   # Class 3 — Grade A = 50% WR, ROI +195.5%
    4: -3.0,   # Class 4 — Grade A = 16.7% WR, ROI -57.5%
    5: +3.0,   # Class 5 — Grade A = 36.4% WR, ROI +213.1%
    6: -1.0,   # Class 6 — low grade, noisy form
    7: -4.0,   # Class 7 — seller/claimer, unreliable
}


# ─────────────────────────────────────────────────────────────────────────────
# SUB-SCORE PREDICTIVE POWER  (ranked by Pearson correlation, n=60)
# ─────────────────────────────────────────────────────────────────────────────

SUB_SCORE_PREDICTIVE_POWER: list[dict] = [
    {"component": "Trainer Intent",  "pearson_r": +0.2693, "signal": "SIGNAL",  "ceiling_current": 15, "ceiling_recommended": 20},
    {"component": "Suitability",     "pearson_r": +0.1209, "signal": "WEAK",    "ceiling_current": 25, "ceiling_recommended": 25},
    {"component": "Form Quality",    "pearson_r": +0.0493, "signal": "NOISE",   "ceiling_current": 40, "ceiling_recommended": 30},
    {"component": "Race Context",    "pearson_r": -0.0767, "signal": "NOISE",   "ceiling_current": 15, "ceiling_recommended": 10},
    {"component": "Market Overlay",  "pearson_r": -0.1218, "signal": "INVERSE", "ceiling_current":  5, "ceiling_recommended":  0},
]


# ─────────────────────────────────────────────────────────────────────────────
# GOLDEN ZONE COMBO  (Grade A + Hurdle + Class 5)
# ─────────────────────────────────────────────────────────────────────────────

GOLDEN_ZONE: dict = {
    "grade":       "A",
    "race_type":   "hurdle",
    "race_class":  5,
    "win_rate_pct": 40.0,
    "roi_pct":      261.6,
    "n":            5,
    "confidence":   "LOW — needs n>=20 to validate",
    "bonus_points": 5.0,
}
