"""
email_render.py — turn the system's plain-text reports into styled HTML email.

Every email in the system (morning briefing, market update, evening audit,
weekly learning report, reliability alerts) is assembled as plain text using a
shared visual vocabulary:

    ═════ / ===== / ─────   separator rules
    ■ SECTION TITLE          section headers (morning briefing)
    ==== SECTION ====        section headers (audit / market update)
    • bullet                 bullet points
    ⚠ / 🚨                   warnings / alerts
    Key: value | Key: value  inline stat rows

This module reads that vocabulary and renders a clean, responsive HTML email —
branded header, section cards, colour-coded confidence and warnings, monospace
content blocks so tabulate grids and column-aligned rows stay aligned — while
keeping the original text intact as the plain-text MIME part. Nothing about the
report builders changes; they keep emitting the same text and it keeps working
in clients that block HTML.

Public API:
    to_html(title, subtitle, body_text, degraded_note="") -> str
"""

from __future__ import annotations

import html
import re

# --- palette ---------------------------------------------------------------
_BG = "#eef0f3"
_CARD = "#ffffff"
_INK = "#1f2933"
_MUTED = "#6b7280"
_ACCENT = "#0f766e"          # teal — brand accent
_HEADER_BG = "#1f2933"       # dark slate header bar
_DIVIDER = "#e3e6ea"
_AMBER = "#b45309"
_RED = "#b91c1c"
_GREEN = "#15803d"
_BLUE = "#1d4ed8"

_SEP_CHARS = set("═─=-_—•·")  # chars that, alone, make a separator rule


def _is_sep(line: str) -> bool:
    s = line.strip()
    return len(s) >= 4 and set(s) <= _SEP_CHARS


def _confidence_colour(text: str) -> str | None:
    """Pick a colour for a line that reports a confidence/agreement verdict."""
    u = text.upper()
    if "DISAGREE" in u:
        return _RED
    if re.search(r"\bHIGH\b", u) and "CONFIDENCE" in u:
        return _GREEN
    if "MEDIUM-HIGH" in u or re.search(r"\bMEDIUM\b", u):
        return _BLUE
    if "AGREE" in u:
        return _GREEN
    return None


def _line_html(raw: str) -> str:
    """Render one content line to HTML, colour-coding warnings and verdicts.

    Whitespace is preserved by the enclosing pre-wrap block so column-aligned
    rows and tabulate grids keep their shape.
    """
    esc = html.escape(raw)
    stripped = raw.strip()
    if not stripped:
        return '<div style="height:8px;line-height:8px;">&nbsp;</div>'  # spacer

    colour = None
    weight = "400"
    if "🚨" in raw or "ALERT" in raw.upper():
        colour, weight = _RED, "700"
    elif "⚠" in raw or "DEGRADED" in raw.upper() or "WARNING" in raw.upper():
        colour, weight = _AMBER, "600"
    elif stripped.startswith("Confidence:") or "CONFIDENCE" in raw.upper() or "Agreement:" in raw:
        colour = _confidence_colour(raw)
        weight = "600" if colour else "400"

    style = "white-space:pre-wrap;"
    if colour:
        style += f"color:{colour};font-weight:{weight};"
    return f'<div style="{style}">{esc}</div>'


def _strip_banner(lines: list[str]) -> list[str]:
    """Drop a leading title banner (sep / title / sep) — HTML supplies its own."""
    if not lines or not _is_sep(lines[0]):
        return lines
    # Skip the first separator, then everything up to and including the next one.
    i = 1
    while i < len(lines) and not _is_sep(lines[i]):
        i += 1
    if i < len(lines):  # landed on the closing separator
        i += 1
    return lines[i:]


def _strip_footer(lines: list[str]) -> list[str]:
    """Drop a trailing '---' / 'Generated by …' footer — HTML supplies its own."""
    for idx in range(len(lines) - 1, -1, -1):
        s = lines[idx].strip()
        if s == "---" or s.startswith("---"):
            tail = "\n".join(lines[idx:]).lower()
            if "generated by" in tail:
                return lines[:idx]
    return lines


def _split_sections(body_text: str) -> list[tuple[str | None, list[str]]]:
    """Split body text into (header|None, content_lines) sections.

    A header is either a line beginning with '■' or a line sandwiched between
    two separator rules (the '==== TITLE ====' convention). Separator rules are
    consumed as delimiters. Leading title banner and trailing footer are removed.
    """
    lines = body_text.replace("\r\n", "\n").split("\n")
    lines = _strip_footer(_strip_banner(lines))

    sections: list[tuple[str | None, list[str]]] = []
    header: str | None = None
    content: list[str] = []

    def flush() -> None:
        nonlocal header, content
        # Trim leading/trailing blank lines in the content block.
        while content and not content[0].strip():
            content.pop(0)
        while content and not content[-1].strip():
            content.pop()
        if header is not None or content:
            sections.append((header, content))
        header, content = None, []

    n = len(lines)
    for i, line in enumerate(lines):
        prev_sep = i > 0 and _is_sep(lines[i - 1])
        next_sep = i + 1 < n and _is_sep(lines[i + 1])
        stripped = line.strip()

        if _is_sep(line):
            continue  # delimiter — never rendered directly

        is_header = stripped.startswith("■") or (prev_sep and next_sep and stripped)
        if is_header:
            flush()
            header = stripped.lstrip("■").strip()
            continue

        content.append(line)

    flush()
    return sections


def _render_section(header: str | None, content: list[str]) -> str:
    body_lines = "".join(_line_html(l) for l in content)
    if not body_lines and not header:
        return ""

    head_html = ""
    if header:
        head_html = (
            f'<div style="font-size:13px;font-weight:700;letter-spacing:.5px;'
            f"text-transform:uppercase;color:{_ACCENT};"
            f'border-left:3px solid {_ACCENT};padding:2px 0 2px 10px;margin:0 0 10px 0;">'
            f"{html.escape(header)}</div>"
        )
    content_html = (
        f'<div style="font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;'
        f'font-size:13px;line-height:1.55;color:{_INK};">{body_lines}</div>'
    )
    return (
        f'<div style="background:{_CARD};border:1px solid {_DIVIDER};border-radius:10px;'
        f'padding:16px 18px;margin:0 0 14px 0;">{head_html}{content_html}</div>'
    )


def to_html(title: str, subtitle: str, body_text: str, degraded_note: str = "") -> str:
    """Render a full HTML email document from a plain-text report body.

    Args:
        title:    main header line (e.g. "Racing Intelligence").
        subtitle: secondary header line (e.g. "Morning Briefing — Tue 2026-06-10").
        body_text: the existing plain-text report; parsed into styled sections.
        degraded_note: if non-empty, shown as a red banner under the header.

    Returns a complete HTML string suitable for the text/html MIME part.
    """
    sections = _split_sections(body_text)
    sections_html = "".join(_render_section(h, c) for h, c in sections)
    if not sections_html.strip():
        # Nothing parsed — fall back to the whole body in one monospace card.
        sections_html = _render_section(None, body_text.split("\n"))

    degraded_html = ""
    if degraded_note.strip():
        degraded_html = (
            f'<div style="background:#fef2f2;border:1px solid #fecaca;color:{_RED};'
            f'border-radius:10px;padding:12px 16px;margin:0 0 14px 0;font-size:13px;'
            f'font-weight:600;white-space:pre-wrap;">{html.escape(degraded_note.strip())}</div>'
        )

    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html.escape(title)}</title>
</head>
<body style="margin:0;padding:0;background:{_BG};">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:{_BG};">
    <tr><td align="center" style="padding:24px 12px;">
      <table role="presentation" width="600" cellpadding="0" cellspacing="0"
             style="width:600px;max-width:100%;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
        <tr><td style="background:{_HEADER_BG};border-radius:12px 12px 0 0;padding:22px 24px;">
          <div style="color:#ffffff;font-size:20px;font-weight:700;letter-spacing:.3px;">{html.escape(title)}</div>
          <div style="color:#9aa5b1;font-size:13px;margin-top:4px;">{html.escape(subtitle)}</div>
          <div style="height:3px;width:46px;background:{_ACCENT};border-radius:2px;margin-top:14px;"></div>
        </td></tr>
        <tr><td style="padding:18px 16px 6px 16px;">
          {degraded_html}
          {sections_html}
        </td></tr>
        <tr><td style="padding:6px 24px 26px 24px;">
          <div style="border-top:1px solid {_DIVIDER};padding-top:12px;color:{_MUTED};font-size:11px;line-height:1.5;">
            Racing Intelligence System · automated report · do not reply.<br>
            Selections are model output for research, not betting advice.
          </div>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>"""
